### ISSUE TITLE
Installation Issues on 2016 12 inch MacBook 

### ISSUE THREAD

**Issue by vri360** [imbushuo/mac-precision-touchpad#102]
I have a 2016 Macbook 12 inch, & am trying to install this on my Bootcamp Windows partition. I did not get any errors while following the installation guide (able to run the CER & INF files), but am unable to actually use precision touchpad on my built in touchpad.

Am I missing any steps or incorrectly installing the program for a built in touchpad? Any guidance would be much appreciated!

<img width="455" alt="screen shot 2018-07-23 at 09 22 20" src="https://user-images.githubusercontent.com/41580177/43079004-feb620da-8e59-11e8-837d-d2fbc541e511.png">

**Comment by imbushuo** [comment]
Because the driver is not signed yet. (You need SPI driver, not USB)

**Comment by vri360** [comment]
Thanks for the response! How can I instal/setup SPI driver?

**Comment by imbushuo** [comment]
If you want to install the SPI drive right now, you need to enable test signing and compile the driver, then install it like the USB driver. Our EV certificate is still processing, so in the future, the installation process will be significantly streamlined.
