### ISSUE TITLE
Macbook13,3 Device ID

### ISSUE THREAD

**Issue by mardibiase** [imbushuo/mac-precision-touchpad#104]
As title suggests, for Macbook13,3 (Pro 15" 2016)
```
 Product ID:	0x0278
 Vendor ID:	0x05ac (Apple Inc.)
```

Screenshot:

<img width="498" alt="screen shot 2018-07-24 at 19 22 42" src="https://user-images.githubusercontent.com/5766743/43155163-f84dbdf2-8f76-11e8-81ce-d6abebea7e42.png">

**Comment by imbushuo** [comment]
0x0278 is supported with the SPI driver as of now.
