### ISSUE TITLE
MacBook Air 4,1 (Mid 2011, 11-inch) Not Working (Device ID attached)

### ISSUE THREAD

**Issue by matthewgregg** [imbushuo/mac-precision-touchpad#106]
Not sure if support has been added for the 2011 MacBook Air but I'm getting a "Device cannot start (Code 10)" error when updating the driver.

![dm](https://user-images.githubusercontent.com/3027494/43358348-1e4ffcc2-9288-11e8-89a0-ef6bea048038.PNG)

Device IDs:
Apple Multitouch
USB\VID_05AC&PID_024A&REV_0209&MI_01
USB\VID_05AC&PID_024A&MI_01

Apple Multitouch Mouse
USB\VID_05AC&PID_024A&REV_0209&MI_02
USB\VID_05AC&PID_024A&MI_02

You were looking for trace files in an old issue, so here's mine
[Bring-up.zip](https://github.com/imbushuo/mac-precision-touchpad/files/2238102/Bring-up.zip)

Let me know if you need anything else

**Comment by imbushuo** [comment]
I pushed a update (not yet signed off the release but it is installation) for your device. Please try https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_build/results?buildId=3734 and see if it works.

**Comment by imbushuo** [comment]
Also linked to #235
