### ISSUE TITLE
Macbook Pro 12,1 (Retina, 13-inch, Early 2015 ) -- Device ID attached

### ISSUE THREAD

**Issue by hcpark509** [imbushuo/mac-precision-touchpad#108]
For Macbook Pro 21,1 (Early 2015)

![image](https://user-images.githubusercontent.com/39859956/43419111-0974cf5e-947b-11e8-98ac-b7e25380f8ee.png)

![image](https://user-images.githubusercontent.com/39859956/43419118-0e6402be-947b-11e8-87cd-1726c364ebe4.png)

Thank you for your work.

**Comment by imbushuo** [comment]
Implemented in the SPI driver.
