### ISSUE TITLE
Signed SPI driver

### ISSUE THREAD

**Issue by enricmarques** [imbushuo/mac-precision-touchpad#109]
Hi, 

I've a MacBook 12" 2017 (Id: MacBook10,1, Model A1534).

I've successfully compiled the SPI driver, but I cannot install it without enabling Test-Signing in my computer. I've also tried the SPI driver from the CI builds, with same result. It seems it is signed with the WDK test signature.

I use the laptop inside our organization, and I'm not allowed to enable test-signing.

I've tried to enable test-signing to try the SPI driver, and it works perfectly, but I only used it a couple of minutes. Are you going to release a signed SPI driver?

Thanks!

**Comment by 1132719438** [comment]
Can you share the compiled SPI driver?

**Comment by enricmarques** [comment]
Hi @1132719438 ,

You can get it from the continuous integration builds:
https://ptp-release.imbushuo.net/

![image](https://user-images.githubusercontent.com/903431/43507972-e27b48c0-956e-11e8-901e-26299465a81d.png)

Enric

**Comment by ww123td** [comment]
Hi @enricmarques The CI builds seem to have not been updated to date and made my trackpad recognized as a touchscreen (which is an already resolved issue). I don't have access to my workstation so I cannot compile it myself. It would be great if you can share yours so I can make mine working again.

Thanks!

**Comment by enricmarques** [comment]
Last CI build is from July 14th, which is when the last commit was done on the repository. My build will be identical.

**Comment by ww123td** [comment]
Hi @enricmarques the last CI build is 3ba51c8, which was the second commit of the day. The author then followed up with a series of fixes including the bug that identified the touchpad as a touchscreen. Again, if you are willing to share your build that would be super helpful, thanks!

**Comment by enricmarques** [comment]
Hi @ww123td,

Here is the driver, built on my computer yesterdar, that worked fine on my MacBook 12" 2017:

[AmtPtpDeviceSpiKm.zip](https://github.com/imbushuo/mac-precision-touchpad/files/2250257/AmtPtpDeviceSpiKm.zip)

Enric

**Comment by 1132719438** [comment]
This build is from the latest commit, and it works on MacBook 15'' 2017

https://ptp-release.imbushuo.net/Apple%20PTP%20Trackpad%20Build/702e8c518ab052272c2f5f62c33d12a76eb160e2/

**Comment by 1132719438** [comment]
It seems Swipe left or right with two fingers to show the previous or next page not works.

**Comment by vdroid711** [comment]
Thanks guys! 
All windows gestures are working perfectly!

**Comment by Kent-Narun** [comment]
Thanks guys. Now the driver show up in device manager for MacBook Pro 2016 🙏🏼🙏🏼🙏🏼...

**Comment by Kent-Narun** [comment]
@enricmarques I use your driver but my computer have blue screen after wake up from sleep (unexpected_kernel_mode_trap after wake up from sleep). Do you have any fix for this? I'm using Macbook Pro 2016 touch bar (13,2).

**Comment by enricmarques** [comment]
Hi @Kent-Narun,

I’m not the developer of this driver, just tried it. You should create a new issue so the project developer can take a look.

Enric

**Comment by imbushuo** [comment]
@Kent-Narun This is a known issue (see the wakeup thread).

**Comment by imbushuo** [comment]
The EV-signed driver will be available about a month later (well, the procedure is far more complicated than a normal signed driver).

**Comment by phu54321** [comment]
Is there any ETA for signed driver?

**Comment by imbushuo** [comment]
@xeijin We have some issue on entity presence validation and is currently working on that.

**Comment by steven-ray** [comment]
Hmm, can's seem to get the SPI driver loaded for the device.  Have MacBookPro14,1 and downloaded a few versions above.  Verified the entry in the .inf file.  Installed certs and .inf.  Enabled testsigning on.  Rebooted the system and then try to update the driver by browsing to the driver location.  Windows just says I have the best driver installed and will not update.  Any thoughts?

**Comment by xeijin** [comment]
@imbushuo any updates? Still uncomfortable with leaving my computer in test mode given security risks...

**Comment by imbushuo** [comment]
SPI drivers are signed as of today.
