### ISSUE TITLE
Support Macbook Pro 15" 2018 (MacbookPro15,1)

### ISSUE THREAD

**Issue by phamminhtris** [imbushuo/mac-precision-touchpad#111]
<img width="371" alt="screen shot 2018-08-06 at 9 37 24 pm" src="https://user-images.githubusercontent.com/13151744/43749271-676a616e-99c1-11e8-9435-292c68b67a65.png">
<img width="308" alt="screen shot 2018-08-06 at 9 37 49 pm" src="https://user-images.githubusercontent.com/13151744/43749275-6aedf242-99c1-11e8-9267-140b7af70bcc.png">

**Comment by MacDragon** [comment]
A vote for trying to include this and seeing what happens, 2018 appears to be being reported as a USB device, going via t2 acting as a usb hub.. hopefully this doesn't end up complicating matters much.

**Comment by imbushuo** [comment]
Supported as of today
