### ISSUE TITLE
MacBook Pro 15" 2017 SPI  ID

### ISSUE THREAD

**Issue by err5** [imbushuo/mac-precision-touchpad#115]
<img width="575" alt="screen shot 2018-08-21 at 1 41 40 pm" src="https://user-images.githubusercontent.com/40775863/44397235-4645ad80-a548-11e8-8bdd-4da9ec190886.png">

Apple Internal Keyboard / Trackpad:

  Product ID:	0x0278
  Vendor ID:	0x05ac (Apple Inc.)
  ST Version:	8.96
  MT Version:	4.69
  Serial Number:	FM77304003KGJCPAA+WNZ
  Manufacturer:	Apple Inc.
  Location ID:	0x01000000

**Comment by imbushuo** [comment]
0x0278 is supported with the SPI driver.
