### ISSUE TITLE
device ID for 2016 MacBookPro13,3

### ISSUE THREAD

**Issue by wdale93** [imbushuo/mac-precision-touchpad#117]
Great work.

<img width="797" alt="spi info" src="https://user-images.githubusercontent.com/42753025/44687067-161a7500-aa48-11e8-8e4d-9b913d9677d1.png">

Hopefully this will help.

**Comment by cubesu9ar** [comment]
PID 0x0278 already included in the .inf file.
Have you tried the SPI driver? You can get the SPI driver from [This thread](https://github.com/imbushuo/mac-precision-touchpad/issues/109)

The author is working to enable the signed driver, so we need to enable test signing at this moment, to make the SPI driver work
