### ISSUE TITLE
Device ID for MacBookPro13,2 (MacBook Pro 13 inch, 2016)

### ISSUE THREAD

**Issue by fabianthdev** [imbushuo/mac-precision-touchpad#121]
product id:	0x0277
vendor id:	0x05ac (Apple Inc.)

<img width="863" alt="image" src="https://user-images.githubusercontent.com/26281795/45417851-6833db00-b683-11e8-89ea-3c98236b2bf5.png">

**Comment by cubesu9ar** [comment]
PID 0x0276 already included in the .inf file.
Have you tried the SPI driver? You can get the SPI driver from [This thread](https://github.com/imbushuo/mac-precision-touchpad/issues/109)

The author is working to enable the signed driver, so we need to enable test signing at this moment, to make the SPI driver work
