### ISSUE TITLE
Device ID for MacBookPro 14,1 (MacBook Pro 13 inch none touch bar, 2017)

### ISSUE THREAD

**Issue by kei1603** [imbushuo/mac-precision-touchpad#125]
Product ID:	0x0276 
 Vendor ID:	0x05ac (Apple Inc.)
<img width="750" alt="screen shot 2018-09-20 at 2 54 55 pm" src="https://user-images.githubusercontent.com/43443067/45820089-4c18e500-bce6-11e8-9f7c-18eb64c71d32.png">

**Comment by cubesu9ar** [comment]
PID 0x0276 already included in the .inf file.
Have you tried the SPI driver?  You can get the SPI driver from [This thread](https://github.com/imbushuo/mac-precision-touchpad/issues/109)

The author is working to enable the sign, but we need to enable test signing at this moment, to make the SPI driver work
