### ISSUE TITLE
Macbook Air Early 2015

### ISSUE THREAD

**Issue by jonalbo** [imbushuo/mac-precision-touchpad#126]
Still can't seem to get the driver to work. Not sure if I'm downloading it from the wrong file or something but tried to upgrade the driver for Apple SPI touchpad to the Apple Precision Touchpad Device but can't get it to work. SPI Info attached.
![screen shot 2018-09-10 at 11 02 25 am](https://user-images.githubusercontent.com/43075556/45821226-a9953d80-bcb6-11e8-8412-e430eda8d1a5.png)

**Comment by JamesLee5782** [comment]
I was testing earlier and I have no idea why what I did made it work but here it is:
Downloaded and installed the latest build 1806. Didn't work
Downloaded and installed 1802 Released feb 2nd. Trackpad stopped working
Went to device manager, trackpad properties, update driver, let me pick from list of available drivers, and selected HID compliant touch pad. And now it's working beautifully.

Could just try changing the driver to the HID compliant touchpad after installing release 1806 and seeing if that works. 

On early macbook air 2015 model A1466

**Comment by imbushuo** [comment]
0x0291 is supported with the SPI driver as of now.
