### ISSUE TITLE
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) Device ID

### ISSUE THREAD

**Issue by flagersinc** [imbushuo/mac-precision-touchpad#127]
The new model of MacBook Pro routes trackpad and keyboard data through the new embedded T2 chip, this is why the device is listed within the USB Device Tree of the iBridge Bus.
<img width="863" alt="screen shot 2018-09-20 at 1 35 05 pm" src="https://user-images.githubusercontent.com/37091226/45836261-4f0dd880-bcda-11e8-86d1-7e462cd3e6fc.png">
<img width="863" alt="screen shot 2018-09-20 at 1 36 54 pm" src="https://user-images.githubusercontent.com/37091226/45836262-4f0dd880-bcda-11e8-9a90-8a1fca4f72b4.png">

**Comment by FudiHub** [comment]
What else do you need to make your great driver support the MBP mid 2018 13 inch model? I am really looking forward to it. Thanks! Donation incoming.

**Comment by soooch** [comment]
Could we use the existing USB driver for this, or would some relatively drastic changes have to be made on account of the T2?

**Comment by adriankwil** [comment]
> Could we use the existing USB driver for this, or would some relatively drastic changes have to be made on account of the T2?

I have tried to install the current release for the USB trackpad but I get the error " device could not start error code 10 ". I expect this is something to do with the T2 and/or my incompetence with installation XD

**Comment by imbushuo** [comment]
Supported as of today
