### ISSUE TITLE
Using driver for non apple computer+ Bluetooth magic trackpad?

### ISSUE THREAD

**Issue by alexmore214** [imbushuo/mac-precision-touchpad#128]
Hi 

I'm interested in seeing what it takes to make the apple magic trackpad work for native windows computers with a bluetooth magic trackpad. Any suggestions? I have some CS background and would be interested in helping out.
Thanks.

**Comment by imbushuo** [comment]
@alexmore214 With the practice of SPI trackpad, I believe the basic procedure is attaching the bluetooth-enumerated HID device, register driver as well as **Internal IOCTL routine** (Non-internal IOCTL routine won't work. Hence the driver has to be resided in kernel). Then everything should be the same as SPI except the packet structure.

Still working on SPI driver, I will see if this is possible when I have some time later.

**Comment by codycodes** [comment]
Hey, now that the SPI driver seems to be working, how are we looking for this? I would also be interested in contributing if I can figure out how this works. I've never done lower-level stuff but I'm assuming there's a decent amount of abstraction that exists since there are many bluetooth devices on the market :). Thanks for developing this!

**Comment by m4gr4th34** [comment]
If you can make my magicpad 2 work smooth as silk on win10, I would be ever so grateful.  :)

**Comment by VideoPlayerCode** [comment]
Sounds good. Bluetooth magic trackpads (external) are great.

**Comment by andrewahlberg** [comment]
Just bought a Magic Trackpad 2 and it works great wired! Was just wondering how close we are to the wireless Bluetooth support? Would be so happy if that would work.

**Comment by cukabeka** [comment]
This would be very interesting for me, too. Plus, I don't get from the available information whether I can attach a magic trackpad 1 A1339 (not the 2 with force touch) to a default PC? And if so, via Bluetooth or via USB?

**Comment by carlitorendon** [comment]
> This would be very interesting for me, too. Plus, I don't get from the available information whether I can attach a magic trackpad 1 A1339 (not the 2 with force touch) to a default PC? And if so, via Bluetooth or via USB?

I would also be pretty interested in seeing if a Trackpad Gen 1 can be re-used on Windows.

**Comment by swirle13** [comment]
I have a magic pad 1, A1339, which I installed this driver to use, but I can't get anything working besides mouse movement and clicking. There are no gestures, no two-finger right click, etc. Is there anything I need to do to get these working? I had it connected via bluetooth before installing the driver, could that have affected anything? Thanks. Trying to get this to work for my wife with wrist pain when using a laptop.

**Comment by therealjohnsnow** [comment]
> I have a magic pad 1, A1339, which I installed this driver to use, but I can't get anything working besides mouse movement and clicking. There are no gestures, no two-finger right click, etc. Is there anything I need to do to get these working? I had it connected via bluetooth before installing the driver, could that have affected anything? Thanks. Trying to get this to work for my wife with wrist pain when using a laptop.

same here. i installed the driver prior to connecting via bluetooth, but it is functioning just as you described, a super basic mouse essentially. Seems like not much info of support nor success with A1339 :(

i'd be happy to know if you found a way around this. thanks a mil!

**Comment by StudioRewired** [comment]
Is there still no support for model A1339?
