### ISSUE TITLE
Any way to uninstall the drivers? They have incompatibility problems with DirectX 9

### ISSUE THREAD

**Issue by xavcrack** [imbushuo/mac-precision-touchpad#129]
Hi. I have installed the Drivers.2358.zip since newer drivers didn't work. This old drivers worked just fine. But what a surprise I had when I tried to run Gears of War or Halo or Halo 2, they will not boot at all. Because of having no idea how to uninstall the drivers I did a complete fresh Windows 10 install on my Mac, inmediately played all this games from my external drive and they worked just fine. Then I installed the drivers again, and BOOM neither of this games wanted to boot. I'm completely sure there is some incompatibility between this drivers and DirectX 9.0c, so installing this drivers makes your Mac completely uncapable of running older games (that are the most I play since my Mac is not very powerful). Any ideas?

**Comment by imbushuo** [comment]
Right-click the device in device manager, click "Remove Device" and make sure you click on the option of removing driver as well.

Then scan hardware changes once.
