### ISSUE TITLE
Device ID, MacBook Pro 15 inch, Mid 2015, with retina screen

### ISSUE THREAD

**Issue by chemPolonium** [imbushuo/mac-precision-touchpad#131]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/17716004/46252794-5aae8b80-c4a0-11e8-9dc7-290dadb534ad.png">

**Comment by cycorey** [comment]
yes, my mac(MacBook Pro 15 inch, Mid 2015, with retina screen), Device ID is the same.

I installed the usb version, but not see any thing more in the control panel.

If @imbushuo could merge the support for MacBook Pro (15-inch, 2015), It will be a great help to me!

**Comment by Terry2001** [comment]
my mac is same. hope for support, thanks very very much~~~

**Comment by imbushuo** [comment]
We actually have a few code for Mid 2015 device merged in. I don’t have the device (the original device owner has transferred the device to someone else), so it may be tricky for me to test it at this moment.

Plus I am dealing with intensive academic workload. If there is any update (likely summer), I will let you know.

**Comment by Terry2001** [comment]
Thanks for reply soon.  Maybe I can research how to test the driver on my device. I will try it in a few days. Could you tell me where I can find the document about setting a testing or development environment?

**Comment by imbushuo** [comment]
Here should have everything you need: https://docs.microsoft.com/en-us/windows-hardware/drivers/

By the way, there is no need for enabling test signing on UMDF drivers (in your case). And you don’t need to set up test agent (that’s for automation test).

For some reason, user-mode debugger never works for this driver, so most time I used WPP tracing and TraceView to help me diagnosing issues: https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/traceview

**Comment by Terry2001** [comment]
@imbushuo Thanks for your great help.  After modify some code,  the touchpad is already working well in debug version.  But I‘m not sure the code change is correct.  I will debug it more.

commit link as below, could you review it if you have time.
https://github.com/Terry2001/mac-precision-touchpad/commit/7a941b5daee3ad53feb2a1b890402b200548187b?diff=split

**Comment by imbushuo** [comment]
Hi,

This looks good to me. Could you kindly send me a PR?

Thanks,
Bingxing Wang

Sent from my iPhone

On Apr 14, 2019, at 12:20 PM, Terry <notifications@github.com<mailto:notifications@github.com>> wrote:


@imbushuo<https://github.com/imbushuo> Thanks for your great help. After modify some code, the touchpad is already working well in debug version. But I‘m not sure the code change is correct. I will debug it more.

commit link as below, could you review it if you have time.
Terry2001@7a941b5?diff=split<https://github.com/Terry2001/mac-precision-touchpad/commit/7a941b5daee3ad53feb2a1b890402b200548187b?diff=split>

**Comment by Terry2001** [comment]
Let me test it a week and check some documents to confirm the modification is right.  Then I will send a PR.

**Comment by imbushuo** [comment]
Merged through https://github.com/imbushuo/mac-precision-touchpad/pull/179.
