### ISSUE TITLE
Device ID for 2015 Retina MacBook Pro 13" 

### ISSUE THREAD

**Issue by jackbwkr** [imbushuo/mac-precision-touchpad#135]
Tried a couple of releases with no luck. If there's any other ways I can help with this project hmu!

  Product ID:	0x0273
  Vendor ID:	0x05ac (Apple Inc.)

**Comment by imbushuo** [comment]
0x0273 validated. Are you installing SPI driver and have test signing on?

**Comment by magedx20** [comment]
Hello ,
did u managed to get it to work ? i have same model product and vendor ID 0x0273
but not working with me .

**Comment by djakupovic** [comment]
Same here, searched for other Drivers posted on other issues and closed issues but does not work

**Comment by imbushuo** [comment]
0x0273 should be supported with the signed SPI driver.
