### ISSUE TITLE
New build or build instructions?

### ISSUE THREAD

**Issue by colemickens** [imbushuo/mac-precision-touchpad#137]
Hello. First, a big thank you for working on this.

A few questions:

1. Can you publish a new build with signed drivers?
2. If not, can you give me a quick synopsis of the build / manual install process? I can try to get it running and then send a PR for `CONTRIBUTING.md` or something like that.

**Comment by imbushuo** [comment]
- Install latest Windows SDK and WDK
- Build the driver using Visual Studio
