### ISSUE TITLE
Medical Emergency 

### ISSUE THREAD

**Issue by imbushuo** [imbushuo/mac-precision-touchpad#141]
I am in medical emergency, the project will restore once I get fine.

Update: Hospitalized. ETA unknown.
Update 2: Discharged from hospital. Treatment continues...

**Comment by josefrvaldes** [comment]
You don't have to worry about the project. Just focus on getting well.

I'll send you strenght from Spain!

**Comment by Undre4m** [comment]
You have an awesome project here. Hope you get well soon mate!

**Comment by kazenoai** [comment]
The project is amazing. I hope you get fine as soon as possible.

**Comment by lime517** [comment]
Sorry to hear that! Get well soon.

**Comment by imbushuo** [comment]
Back to work.
