### ISSUE TITLE
My MacBook Air 2017(13-inch) cannot activate the driver. (Attached my install steps)

### ISSUE THREAD

**Issue by primelyw** [imbushuo/mac-precision-touchpad#143]
I tried to install your driver according to your instructions. After installing it, I cannot move the cursor using my internal touchpad.
     Here is my installing steps.
     1) Download Drivers.2358.zip.
     2) Follow your instructions in "README.md"
     3) Update my driver in Windows Device Manager

     Please Help,Thanks!
     
![213153de-9dd6-43ca-a029-82c5c2bae71c](https://user-images.githubusercontent.com/32811464/47196687-576a3980-d394-11e8-950d-168fcc728c0d.png)

![l oby _lj7xzoy5lbk8wj](https://user-images.githubusercontent.com/32811464/47196762-b5971c80-d394-11e8-90e7-bac9bd19a2ef.png)

**Comment by mjw3** [comment]
You must enable test signing for the drivers at this time.
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option

**Comment by imbushuo** [comment]
Supported added with https://github.com/imbushuo/mac-precision-touchpad/commit/304062d4d2c2d732115164da87d35931d2d4d756, and will be rolled out with next release. Note that this is a fallback support, feel free to open a ticket if the experience is not optimal.
