### ISSUE TITLE
Macbook Pro 2018 w touchbar

### ISSUE THREAD

**Issue by nerzhulart** [imbushuo/mac-precision-touchpad#144]
![image](https://user-images.githubusercontent.com/623624/47230457-eac25f80-d3d2-11e8-9a70-653036dc0ffb.png)
![image](https://user-images.githubusercontent.com/623624/47230494-04fc3d80-d3d3-11e8-9b75-3410aa57b134.png)

**Comment by imbushuo** [comment]
Supported as of today
