### ISSUE TITLE
Macbook Pro 2018 15 Touchbar 15,1

### ISSUE THREAD

**Issue by naknak237** [imbushuo/mac-precision-touchpad#147]
![screen shot 2018-11-06 at 6 28 50 pm](https://user-images.githubusercontent.com/44821999/48100609-f6df5700-e1f1-11e8-92b4-332be4fb7d12.png)
![screen shot 2018-11-06 at 6 33 43 pm](https://user-images.githubusercontent.com/44821999/48100748-8553d880-e1f2-11e8-8eee-223108b17d65.png)

**Comment by deg0nz** [comment]
Almost identical with 2018 MacBook Pro 13'' with touch bar:

MacBookPro15,2

  Product ID:	0x027b
  Vendor ID:	0x05ac (Apple Inc.)

**Comment by stanczyk4** [comment]
<img width="752" alt="screen shot 2018-11-09 at 8 39 15 pm" src="https://user-images.githubusercontent.com/5186634/48296697-cc92d100-e45f-11e8-9d3e-776d868042ad.png">

Macbook 2018 15" w/ Touch Bar. I have Windows boot camped if you need to remote in for testing. Would love to have real touchpad support to do windows development on my Mac!

**Comment by as-com** [comment]
![image](https://user-images.githubusercontent.com/3819625/48921928-28eaed00-ee71-11e8-8a55-8044a6f6ce44.png)
Here's my 15" 2018 MacBook Pro

**Comment by FZHBW** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/37756813/60380034-df9af580-9a70-11e9-8cca-cdd4b355c953.png">

**Comment by imbushuo** [comment]
Supported as of today
