### ISSUE TITLE
MacBook Pro 15 in Late 2013 (Macbook Pro 11,2) 

### ISSUE THREAD

**Issue by johnmarshall515** [imbushuo/mac-precision-touchpad#148]
Hello, This is a request for support for this MacBook. Here is the needed information: 
<img width="222" alt="screen shot 2018-11-23 at 1 20 24 pm" src="https://user-images.githubusercontent.com/35919593/48960656-3bbdfa00-ef23-11e8-91cb-83d0f87b4704.png">
<img width="297" alt="screen shot 2018-11-23 at 1 20 55 pm" src="https://user-images.githubusercontent.com/35919593/48960657-3bbdfa00-ef23-11e8-9f18-95b309b1f477.png">

**Comment by johnmarshall515** [comment]
Also, I retrieved the HID device ID from the "Apple USB Trackpad" section.

**Comment by jonathanray** [comment]
@johnmarshall515 The 1802.M2 Interim Release works with this model. https://github.com/imbushuo/mac-precision-touchpad/releases/tag/univ-b1-i3
