### ISSUE TITLE
Macbook Pro 2016 15 Touchbar MacBookPro13,3

### ISSUE THREAD

**Issue by zhangwujun666** [imbushuo/mac-precision-touchpad#149]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/19402159/49166944-449c3a80-f32c-11e8-8ca0-db58f6775c3c.png">
<img width="717" alt="image" src="https://user-images.githubusercontent.com/19402159/49166964-51209300-f32c-11e8-8b8d-5acfdcf797d9.png">

**Comment by LukasMendez** [comment]
Did you ever find out if it was possible to use this? I have the exact same machine

**Comment by zhangwujun666** [comment]
Not really, because the installation of SIP has not released yet. And I try to use the developer model to run but failed.

**Comment by imbushuo** [comment]
0278 should be support in https://github.com/imbushuo/mac-precision-touchpad/blob/702e8c518ab052272c2f5f62c33d12a76eb160e2/src/AmtPtpDeviceSpiKm/AmtPtpDeviceSpiKm.inf.
