### ISSUE TITLE
Macbook air mid 2012 (MacBookAir5,2)

### ISSUE THREAD

**Issue by anohren** [imbushuo/mac-precision-touchpad#152]
MacBookAir5,2 
Product ID:	0x024d

**Comment by anohren** [comment]
Can I help make this happen in any way? Test a build or something else?

**Comment by boostinside** [comment]
I also have the same MacBook Air Mid 2012 and the latest release (Build 3665) doesn't seem to work for me. I thought I was doing something wrong during the install. It seems to install fine but I don't see a setting for Touchpad. I'm running Windows 10 Pro. Have you tried other releases to see if any of them work?

**Comment by anohren** [comment]
I have been in contact with the project owner and he has debugged it remotely on my machine. It was a very simple fix and will most likely be added to a release within the year

**Comment by imbushuo** [comment]
@1984dream I pushed a update (not yet signed off the release but it is installation) for your device. Please try https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_build/results?buildId=3734 and see if it works.

**Comment by imbushuo** [comment]
Linked to #235
