### ISSUE TITLE
How does this compare to Magicutilities for Magic Trackpad 2?

### ISSUE THREAD

**Issue by hydrajump** [imbushuo/mac-precision-touchpad#159]
Hi,

I want to use an Apple Magic Trackpad 2 (via USB) with a PC running Windows 10 and without any
driver it just acts like a regular mouse.

The only two solutions I've found are:
- Magicutilities
- mac-precision-touchpad

I've tested Magicutilites but I'm not keen on their subscription basically you're renting the software because after one year if you don't continue paying the software stops working :(

Q1: How does mac-precision-touchpad compare to Magicutilites? I'm unable to try due to Q2 below.

Q2: Is there a cross signed version of the driver because I **cannot** disable SecureBoot and work in testing mode?

Thanks ;)

**Comment by guillefix** [comment]
This driver is a precision driver. The main difference I think is that scrolling is actually smooth/continuous with this driver, while for MagicUtilities/ExtraMagic scrolling actually happens at discrete jumps (even if they try to smooth them out as much as possible..)

Having said that I have tried to install the driver, but it is very sluggish. A lot of the time the touchpad doesn't detect my finger :/ Don't know why

**Comment by m4gr4th34** [comment]
True as stated above.  When it works it's smooth, but it doesn't always detect the fingers, and scrolling is a tricky proposition.  It says the latest release (about a year ago) is not stable for magicpad 2, and that's how i would describe the experience.
