### ISSUE TITLE
Two-fingers scrolling can be hard to trigger

### ISSUE THREAD

**Issue by imbushuo** [imbushuo/mac-precision-touchpad#16]
Need to investigate on that: it can be hard to trigger two-fingers scrolling, but sometimes it will be okay.

**Comment by imbushuo** [comment]
Dynamic sensitivity / better defuzz algorithm should be implemented. Need more cases on finger gestures.

**Comment by imbushuo** [comment]
Fixed with recent update.

**Comment by sirburpalot** [comment]
Two-finger scrolling (as well as simply moving the pointer with one finger) still only works for me half the time with the latest update.
