### ISSUE TITLE
How to use it on Boot Camp

### ISSUE THREAD

**Issue by FinTechNJU** [imbushuo/mac-precision-touchpad#165]
I'm uisng a macbook pro with boot camp installed with win10.
After I install this software. Nothing happend, no UI, no hints, nothing at all.
I'm wondering how to use it on my boot camp

**Comment by FinTechNJU** [comment]
I guess this software is similar to trackpad++. Is it right?

**Comment by markreg** [comment]
How can the touch/press sensitivity be adjusted?

**Comment by Fleischhauer** [comment]
@khalidchawtany How did you actually got it to work? I don't even know if I need usb or spi.. I've a macbook, so it should be integrated? But in the device manager it says usb. oO

**Comment by khalidchawtany** [comment]
Yup I got it to work. I am actually typing this in bootcamp and it works very well. All of the following versions work on my mbp:
- Drivers.2357
- Drivers.2358
- Drivers.2484

![mmc_2019-02-18_12-18-53](https://user-images.githubusercontent.com/1681606/52940347-616a6c00-3377-11e9-9576-1109f66b05f3.png)


![mmc_2019-02-18_12-18-05](https://user-images.githubusercontent.com/1681606/52940321-4bf54200-3377-11e9-9062-28e26e4216dd.png)

**Comment by knittycatkitty** [comment]
> Yup I got it to work. I am actually typing this in bootcamp and it works very well. All of the following versions work on my mbp:
> 
> * Drivers.2357
> * Drivers.2358
> * Drivers.2484
> 
> ![mmc_2019-02-18_12-18-53](https://user-images.githubusercontent.com/1681606/52940347-616a6c00-3377-11e9-9576-1109f66b05f3.png)
> 
> ![mmc_2019-02-18_12-18-05](https://user-images.githubusercontent.com/1681606/52940321-4bf54200-3377-11e9-9062-28e26e4216dd.png)

What Mac are you using?

I'm on a MacBookPro12,1 and I'm having trouble with installation. Turned on TEST mode and disabled driver signature enforcement. I'm using the source code non-signed SPI drivers but I can't get it to install no matter what

**Comment by Fleischhauer** [comment]
Oh, so old?
Did you use the spi ones?

**Comment by khalidchawtany** [comment]
Once I got it to work I never messed with it :)

**Comment by azmatc** [comment]
@Fleischhauer did you manage to get it working? I have same issue as you...i have macbook but it shows my trackpad is USB...so do i use USB version or SPI? Also do you have to turn testsigning mode on?

**Comment by imbushuo** [comment]
Boot Camp interface does not manage this driver. You can change trackpad settings in System Settings > Devices > Touchpad.
