### ISSUE TITLE
Late 2016 MacBook Pro with Touch Bar Device ID

### ISSUE THREAD

**Issue by azsxwazsx** [imbushuo/mac-precision-touchpad#167]
Model identifier: MacBookPro13,2

Under the SPI tab says:
Product ID: 0x0277
Vendor ID: 0x05ac (Apple Inc.)
Are these all you need?

BTW I Love your works :)
Thousand thanks <3

**Comment by imbushuo** [comment]
0277 should be supported in https://github.com/imbushuo/mac-precision-touchpad/blob/702e8c518ab052272c2f5f62c33d12a76eb160e2/src/AmtPtpDeviceSpiKm/AmtPtpDeviceSpiKm.inf.
