### ISSUE TITLE
Is the program alive?

### ISSUE THREAD

**Issue by liyuxi** [imbushuo/mac-precision-touchpad#168]

**Comment by aat83** [comment]
+1 
Any news on upcoming releases? Would love the touchbar 13” 2016-2018 fully supported!

**Comment by knittycatkitty** [comment]
I would love to test. 

As far as I know 2016-2018 are SPI and SPI is working on my 2015.

Going to see if I can get my hands on some.

**Comment by stanczyk4** [comment]
My 2018 pro with touchbar is a usb keyboard. I wanted to give editing the code a try but it didn't seem straightforward. Me and some others posted our hardware in #147 
@knittycatkitty is there any direction you could provide on this? I'd be willing to test or play around with the code a bit.

**Comment by imbushuo** [comment]
Yes it is - just got my T2 MacBook Pro and work is in progress.
