### ISSUE TITLE
SPI trackpads

### ISSUE THREAD

**Issue by knittycatkitty** [imbushuo/mac-precision-touchpad#171]
For anyone who is looking to install this driver on SPI devices such as Macbook12,1 and up

The proper drivers are on his site
https://ptp-release.imbushuo.net/Apple%20PTP%20Trackpad%20(SPI%20Kernel%20Mode)/fc1ebcf0dffc1f921d70a10c461766eb54ccd38b/AmtPtpDeviceSpiKm/x64/Release/

It is not signed so you will need to start Windows 10 with Disabled Driver Signature Enforcement to install it.

Download all the files one by one (unless youre using an FTP client maybe?) and install the INF file. Then go to Device Manager and update the Apple SPI Touchpad to the unsigned Precision Touchpad driver. 

You can also do it all manually via Device Manager, just go to Apple SPI Touchpad, Update Driver, Browse Manually and point to the Precision Touchpad INF file.

It works beautifully, I recommend trying it on 2016 and up, as far as I can tell from the INF file, SPI devices are all the same from 2015 and up mostly.

SPI could most likely be synonymous with Force Touch trackpads.

Many thanks to this guy imbushuo, doing God's work man 

Surprised Precision Touchpad isn't supported on Apple touchpads when the whole initiative can arguably be seen as inspired by Apple's relentless attention to detail with touchpads since 2006.

**Comment by charlespick** [comment]
Tried on my MBP 13,1. Disabled driver signature enforcement, installed driver in device manager. Cursor disappears. Restart doesn't fix it. Any suggestions?

**Comment by knittycatkitty** [comment]
> Tried on my MBP 13,1. Disabled driver signature enforcement, installed driver in device manager. Cursor disappears. Restart doesn't fix it. Any suggestions?

Try a different version, had that issue as well

https://ptp-release.imbushuo.net/Apple%20PTP%20Trackpad%20(SPI%20Kernel%20Mode)/

**Comment by Fleischhauer** [comment]
I tried that one on Macbook Air 2018, didn't work :/

**Comment by Fleischhauer** [comment]
I try some others now. And I get code 10 now, device couldn't be startet.
Also, why is there a folder with another .inf? Do I need that? Do I use that inf or the one in the root folder?

**Comment by knittycatkitty** [comment]
> I try some others now. And I get code 10 now, device couldn't be startet.
> Also, why is there a folder with another .inf? Do I need that? Do I use that inf or the one in the root folder?

What is your device ID? I think for Macbook Air 2018 it was released a few months after the author's last commit on this project.

First step is to put the Apple SPI Touchpad device back to the original drivers.

Also personally I have not seen a difference, I notice all driver packages for Windows come like that though. Not sure why

**Comment by Fleischhauer** [comment]
HID are:
USB\VID_05AC&PID_027A&REV_0913&MI_02
and
USB\VID_05AC&PID_027A&MI_02

Is that right?

**Comment by knittycatkitty** [comment]
> HID are:
> USB\VID_05AC&PID_027A&REV_0913&MI_02
> and
> USB\VID_05AC&PID_027A&MI_02
> 
> Is that right?

Yep let me see what I can do

**Comment by knittycatkitty** [comment]
> HID are:
> USB\VID_05AC&PID_027A&REV_0913&MI_02
> and
> USB\VID_05AC&PID_027A&MI_02
> 
> Is that right?

Can you send me the SPI ones?

**Comment by Fleischhauer** [comment]
Where can I find them? What is SPI? ^^'

**Comment by knittycatkitty** [comment]
> Where can I find them? What is SPI? ^^'

Device Manager -> Human Interface Devices

![image](https://user-images.githubusercontent.com/42597963/53119110-b09dd180-351c-11e9-8933-b35c5a05cd51.png)
Ignore the caption

**Comment by Fleischhauer** [comment]
I don't have a SPI one there.
It looks like this: https://i.imgur.com/3ZaPcAZ.png

**Comment by Fleischhauer** [comment]
Maybe the new trackpad is not spi anymore or something?

**Comment by Fleischhauer** [comment]
The second one is the one that makes my mouse disappear when I deactivate it.

**Comment by knittycatkitty** [comment]
> The second one is the one that makes my mouse disappear when I deactivate it.

I see, can you send me the VID for those? Hard to tell if they are USB or SPI

**Comment by Fleischhauer** [comment]
VID, is that not what I send you?
USB\VID_05AC&PID_027A&REV_0913&MI_02
and
USB\VID_05AC&PID_027A&MI_02

**Comment by knittycatkitty** [comment]
> VID, is that not what I send you?
> USB\VID_05AC&PID_027A&REV_0913&MI_02
> and
> USB\VID_05AC&PID_027A&MI_02

Try this.
https://drive.google.com/open?id=1HK-hbGq4Jd0ns4WnMvXyPoRDtP-R5TMi

**Comment by Fleischhauer** [comment]
I only need that one file?

**Comment by Fleischhauer** [comment]
With that I get a new error: "This is not for x64 based systems"

**Comment by knittycatkitty** [comment]
> With that I get a new error: "This is not for x64 based systems"

https://drive.google.com/open?id=1iakWSv1KgYYI145g0zzLhG5zf1wsNENi

**Comment by Fleischhauer** [comment]
The same error TT

**Comment by knittycatkitty** [comment]
> The same error TT

Last one haha if it doesn't work.. ahh I can't help! 


https://drive.google.com/open?id=1fcsU8V8vSHIE27vWsq31W7f6pSU53T1m

**Comment by Fleischhauer** [comment]
Still the same.
Thanks for trying!

**Comment by Fleischhauer** [comment]
Tried everyone now. None works.

**Comment by ucristian3** [comment]
thanks for the explanation!
I used the same method 3 months ago and i'm using the this driver since that day.
everything work as is should the only big problem I encouter is that I get BSOD when oppening the lid after some time.
Macbook pro (2017) not touchbar 14,1

**Comment by mattbeau** [comment]
> thanks for the explanation!
> I used the same method 3 months ago and i'm using the this driver since that day.
> everything work as is should the only big problem I encouter is that I get BSOD when oppening the lid after some time.
> Macbook pro (2017) not touchbar 14,1

so which one did you install? I tried all of them and keep getting error 10 on my MacBook Pro 2017 nTB 14,1

**Comment by ucristian3** [comment]
> > thanks for the explanation!
> > I used the same method 3 months ago and i'm using the this driver since that day.
> > everything work as is should the only big problem I encouter is that I get BSOD when oppening the lid after some time.
> > Macbook pro (2017) not touchbar 14,1
> 
> so which one did you install? I tried all of them and keep getting error 10 on my MacBook Pro 2017 nTB 14,1

I used this one here....
dont forget to enable TEST MODE     bcdedit -set TESTSIGNING ON    in cmd and and restart PC,after this you can proceed to installation proces

[Macbook.Pro.2016.WinPrecisionTouchpad.zip](https://github.com/imbushuo/mac-precision-touchpad/files/2999674/Macbook.Pro.2016.WinPrecisionTouchpad.zip)

**Comment by mattbeau** [comment]
> thanks for the explanation!
> I used the same method 3 months ago and i'm using the this driver since that day.
> everything work as is should the only big problem I encouter is that I get BSOD when oppening the lid after some time.
> Macbook pro (2017) not touchbar 14,1
> 
> so which one did you install? I tried all of them and keep getting error 10 on my MacBook Pro 2017 nTB 14,1
> 
> I used this one here....
> dont forget to enable TEST MODE     bcdedit -set TESTSIGNING ON    in cmd and and restart PC,after this you can proceed to installation proces
> Macbook.Pro.2016.WinPrecisionTouchpad.zip

Awesome, unfortunately it was an empty zip file but I googled the file name and found it. here it is for others wanting to try it out too :)


[Macbook.Pro.2016.WinPrecisionTouchpad (1).zip](https://github.com/imbushuo/mac-precision-touchpad/files/2999966/Macbook.Pro.2016.WinPrecisionTouchpad.1.zip)

**Comment by thekip** [comment]
> Awesome, unfortunately it was an empty zip file but I googled the file name and found it. here it is for others wanting to try it out too :)
> 
> Macbook.Pro.2016.WinPrecisionTouchpad (1).zip

Hooray, exactly this version works except it always crash the system when you close the lid.

(all other versions get error 10)

**Comment by bpwned** [comment]
> Hooray, exactly this version works except it always crash the system when you close the lid.
> 
> (all other versions get error 10)

I can confirm this on my MacbookPro13,3.

**Comment by imbushuo** [comment]
As of today, SPI trackpad does not require TestSigning. See updated README.

**Comment by carrottopadc** [comment]
Hello! If anyone could help me, that would be fantastic! I used the 2016 mbp drivers for my 2019 15inch mbp and it worked great. I returned that to apple and purchased the 16 inch macbook pro, and not a single one of the drivers work! Spent nearly 4 hours pulling my hair out over this-Any help would be greatly appreciated.
Thanks in advance all,
Andy C
