### ISSUE TITLE
MacBookPro 15,3 (Vega 16/20) USB Device ID's

### ISSUE THREAD

**Issue by goldmastersims** [imbushuo/mac-precision-touchpad#172]
![macbookprovegahw_info](https://user-images.githubusercontent.com/44741216/53617268-5398c000-3b9b-11e9-93fa-aafbff35e166.png)
![screen shot 2019-02-28 at 20 54 32](https://user-images.githubusercontent.com/44741216/53617275-598ea100-3b9b-11e9-9cb4-fc5c3907a4ad.png)
![screen shot 2019-02-28 at 20 54 45](https://user-images.githubusercontent.com/44741216/53617278-5b586480-3b9b-11e9-9727-4e1308928f7d.png)
![screen shot 2019-02-28 at 20 54 58](https://user-images.githubusercontent.com/44741216/53617280-5c899180-3b9b-11e9-99d2-c4e25c59e34b.png)
![screen shot 2019-02-28 at 20 55 06](https://user-images.githubusercontent.com/44741216/53617282-5e535500-3b9b-11e9-946e-48a443e524c0.png)

**Comment by goldmastersims** [comment]
Nothing in the SPI devices

**Comment by imbushuo** [comment]
027c is supported in https://github.com/imbushuo/mac-precision-touchpad/releases/tag/1907-3529, please try and provide feedback.
