### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by Number16** [imbushuo/mac-precision-touchpad#173]
I've tried everything: installing older versions, pre-release drivers (with test mode enabled), half of the time got the confirmation that the installation was complete, but nope, the trackpad driver simply refuses to get replaced (I tried installing it from the Device Manager, but, of course, 'the best drivers are already installed'). What do I do, guys? 

I've got a MacBook 12" 2017

**Comment by introconsulting** [comment]
Same here, my experience is exactly the same to yours.

**Comment by imbushuo** [comment]
MacBook 12 should install the SPI driver.
