### ISSUE TITLE
MacBookPro11,4 (Mid 2015) request

### ISSUE THREAD

**Issue by v8u1er** [imbushuo/mac-precision-touchpad#177]
<img width="389" alt="Screen Shot 1398-01-25 at 11 52 02 AM" src="https://user-images.githubusercontent.com/17022402/56089929-a8746980-5eaf-11e9-996a-0a98d5c673e8.png">

I might be mistaken but it seems that this hardware is not supported right now even though I saw the product Id mentioned somewhere in the code.
I would gladly help in testing the code if needed. Thanks in advance for your great job.

**Comment by imbushuo** [comment]
See https://github.com/imbushuo/mac-precision-touchpad/pull/179
