### ISSUE TITLE
Configure gestures and precision?

### ISSUE THREAD

**Issue by kakyoism** [imbushuo/mac-precision-touchpad#181]
Can we configure the gestures, precision, acceleration, and so on?

**Comment by DrJedikiah** [comment]
Yes, from the touchpad tab under devices in settings.

**Comment by kakyoism** [comment]
Cool. Is it possible to specify the three-finger drag like Trackpad++ does?

**Comment by imbushuo** [comment]
Unfortunately, Precision Touch Pad gestures are defined by Microsoft.
