### ISSUE TITLE
Code 52, certificates installed to machine roots

### ISSUE THREAD

**Issue by nvella** [imbushuo/mac-precision-touchpad#183]
Hi again,

I've added the certificate to the machine Trusted Root Certification Authorities and Trusted Publisher stores. Installing the driver either via Device Manager or right-clicking and selecting install seem to both yield a Code 52 "Windows cannot verify the digital signatures for the driver required" error. Just wondering if I'm missing anything @imbushuo? Windows 10 1903 and MacBook Pro 13" Early 2015.

Kind regards,
Nick

**Comment by imbushuo** [comment]
Resolved as today

**Comment by phyllisstein** [comment]
I just ran into this issue following a clean installation of Windows 10 on a 2019 MacBook Pro. I used the new setup process, which seemed to work fine, but after rebooting there was no cursor on the screen and Device Manager was spitting out this error.

![IMG_0039](https://user-images.githubusercontent.com/2207980/72236013-1c5cb300-35a3-11ea-83a3-7e704cd988f0.jpeg)

**Comment by imbushuo** [comment]
T2 devices need to turn of Secure Boot explicitly as of now. Try to redo the installation again with stale certificates removed from the machine.

Thanks,
Bingxing Wang

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by phyllisstein** [comment]
That worked beautifully, thanks so much.
