### ISSUE TITLE
Does not work for Macbook Pro 2018 13" no touchbar

### ISSUE THREAD

**Issue by JByfordRew** [imbushuo/mac-precision-touchpad#184]
2018 Macbook Pro 13"

Trying a number of means to update the trackpad driver but does not seem to work.  Getting this.

![image](https://user-images.githubusercontent.com/2962258/57132830-b0ca1100-6d98-11e9-8601-52654737496a.png)

**Comment by imbushuo** [comment]
Could you provide the SPI trackpad device ID?

**Comment by HalfbyteHeroes** [comment]
I've got the same issue with my 2016 13 inch model with Touch Bar. How would I find out what the device ID is?

**Comment by imbushuo** [comment]
@HalfbyteHeroes I would blindly assume the device be located under "Apple SPI Device" if you view the Device Manager in connection topology. Otherwise, try to find a "Apple Multi-touch" device, open its properties and check the hardware device ID.

Try installing the latest release first, this one eliminates most confusion in connection technologies and model identification.

**Comment by HalfbyteHeroes** [comment]
Installing the latest release is what I tried first, but the installation failed with the error message already posted in the first comment. I've also manually installed the certificate, but that didn't help either. Manually installing the SPI driver from the previous release worked, but I couldn't use that driver with the `Apple SPI Device`. Anyway, here are the hardware IDs:
```
ACPI\VEN_APP&DEV_000D
ACPI\APP000D
*APP000D
```

Let me know if you need any more info.

**Comment by imbushuo** [comment]
@HalfbyteHeroes APP000D is not the trackpad device. There are three Apple SPI Device which remains unused on MacBook (they are Force Touch components) and you are expected installation failures on those.

You can find either Apple Multi-Touch or some input device under Apple SPI Device (actually a bus device).

**Comment by imbushuo** [comment]
![image](https://user-images.githubusercontent.com/6284353/67881180-6989c680-fb16-11e9-83b5-1e2783654e27.png)

An example of the topology FYI.

**Comment by HalfbyteHeroes** [comment]
Ahh - I've never used that topology view before. Those are the two devices listed under `Apple SPI Trackpad`:

![hid_compliant_mouse](https://user-images.githubusercontent.com/8973940/67882214-30ffe200-fb42-11e9-883a-c07bf27a602b.PNG)
![hid_compliant_vendor_defined](https://user-images.githubusercontent.com/8973940/67882227-35c49600-fb42-11e9-9e9e-eb49918cf29c.PNG)

**Comment by HalfbyteHeroes** [comment]
Yes, that did indeed work! Thank you very much! 🙂
