### ISSUE TITLE
Support for Magic Mouse

### ISSUE THREAD

**Issue by DarrellDD** [imbushuo/mac-precision-touchpad#185]
Would it be interesting to add support to the magic mouse aswell? In terms of smooth scrolling and multitouch. As perhaps a mouse/trackpad hybrid? I'm already really pleased with the work done to the magic trackpad 2, and would like to put my magic mouse to good use too.

**Comment by JLIspace** [comment]
I'm using a first gen magic mouse with the apple bootcamp driver and scrolling works fine.

**Comment by DarrellDD** [comment]
It's not smooth though. Your windows mouse scroll option is being changed aswell which leads to inconsistent scrolling between pointing devices. The Precision Touch prevents this.

**Comment by imbushuo** [comment]
It might work, but using Windows gestures on an arc surface just doesn't make sense to me. Currently I have no plan for supporting Magic Mouse family.
