### ISSUE TITLE
Boot Camp control panel goes away

### ISSUE THREAD

**Issue by TPB3333** [imbushuo/mac-precision-touchpad#186]
Hey, I'm running this driver on my macbook pro mid 2012 in bootcamp. It works great I can't except for the fact I can't change my trackpad settings anymore in the bootcamp control panel. Is this normal? Someone said this driver works best if you disable tap to click, but now I have nowhere to disable this. 

And is there a way to uninstall the driver and get these bootcamp settings back?

Regards
Toon

**Comment by TPB3333** [comment]
Wait, I think I get how this works!
It installed some sort of native windows trackpad. I already got it! :)

**Comment by squalsoft** [comment]
Yes this is important documentation! Settings for this drivers in System settings > Touchpad settings!
