### ISSUE TITLE
model support request for MacBook Air (Retina, 13-inch, 2018)

### ISSUE THREAD

**Issue by kylus** [imbushuo/mac-precision-touchpad#187]
MacBookAir8,1

Product ID：	0x027a
Vendor ID：	0x05ac（Apple Inc.）
ST Version：	9.13

**Comment by kylus** [comment]
![1557207786476](https://user-images.githubusercontent.com/19571061/57274525-281bdf80-70ce-11e9-995a-615b99ed100c.jpg)

**Comment by imbushuo** [comment]
Supported as of today.

**Comment by liustar2008** [comment]
The latest driver doesn't work on the machine.
MacBookAir8,1

Product ID：	0x027a
Vendor ID：	0x05ac（Apple Inc.）
ST Version：	9.13

The driver only support the 0x027d, not 0x027a. please check the driver. Thanks!

**Comment by kylus** [comment]
same problem as liustar2008,
driver can't work on my machine

Product ID：	0x027a
Vendor ID：	0x05ac（Apple Inc.）
ST Version：	9.13

**Comment by kylus** [comment]
> Supported as of today.
same problem as liustar2008,
driver can't work on my machine

Product ID：	0x027a
Vendor ID：	0x05ac（Apple Inc.）
ST Version：	9.13

@imbushuo
