### ISSUE TITLE
MacBookPro 15,1 (2019, Core i9-9880H, Radeon Pro 560X) USB Device ID's

### ISSUE THREAD

**Issue by Uhucream** [imbushuo/mac-precision-touchpad#190]
<img width="1776" alt="MacBookPro15,1_USB" src="https://user-images.githubusercontent.com/16385352/58952161-ed40c080-87cd-11e9-9436-74a4d775d55f.png">

<img width="1792" alt="スクリーンショット 2019-06-05 午後8 08 39" src="https://user-images.githubusercontent.com/16385352/58952261-2e38d500-87ce-11e9-8b19-755ca22fce28.png">

**Comment by Uhucream** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/16385352/58952355-68a27200-87ce-11e9-9406-5b11689d9005.png">


There is no SPI devices on MacBook Pro 2019.

**Comment by imbushuo** [comment]
I have introduced support for this model in https://github.com/imbushuo/mac-precision-touchpad/releases/tag/1907-3529. However, since some calibration data are carried from 13-inch, it may not work optimally. Please try and provide feedback!

**Comment by Uhucream** [comment]
So sorry to be late for responding.
I had installed this driver, it works.
But out range of 13-inch's trackpad couldn't be recognized in my MBP 15-inch.

**Comment by imbushuo** [comment]
@Uhucream Okay so I know that the 15inch have larger space than the 13inch one - will work on a fix for that.

**Comment by Uhucream** [comment]
I see.
By the way, I measure the trackpad size of 15-inch MacBook Pro.
Its size is about 10cm x 15cm.

![2A536772-3D4C-4203-9F0B-55D5C1DC0047](https://user-images.githubusercontent.com/16385352/66534085-1a242c00-eb50-11e9-8714-67dcc2c368c2.jpeg)
![C32716DA-CF65-436F-A9EF-AE7808724B79](https://user-images.githubusercontent.com/16385352/66534086-1abcc280-eb50-11e9-8905-5fb34a21cafe.jpeg)
