### ISSUE TITLE
Driver ID for Macbook Pro 2016 13" (MacbookPro13,1)

### ISSUE THREAD

**Issue by samulien** [imbushuo/mac-precision-touchpad#191]
Hi, here are the details for the MacBook Pro 2016 13" non-touch bar SPI trackpad.

Product ID: 0x0276
Vendor ID: 0x05ac (Apple Inc.)

Thanks very much.

**Comment by imbushuo** [comment]
0276 should be supported in https://github.com/imbushuo/mac-precision-touchpad/blob/702e8c518ab052272c2f5f62c33d12a76eb160e2/src/AmtPtpDeviceSpiKm/AmtPtpDeviceSpiKm.inf.
