### ISSUE TITLE
Not working on Macbook Air 6,2 (mid-2013)

### ISSUE THREAD

**Issue by tonynca** [imbushuo/mac-precision-touchpad#192]
I tried following the instructions and everything got installed but it did not update the stock Apple bootcamp drivers.

I had to go in and manually install the drivers to replace the Apple Multi-touch Device drivers. Unfortunately, it did not work and the error I got was device failed to start.

 Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Intel Core i5
  Processor Speed:	1.3 GHz

Product ID:	0x0291
  Vendor ID:	0x05ac (Apple Inc.)
  ST Version:	1.71
  MT Version:	2.32
  Serial Number:	DQ675057JBKF94RA633
  Manufacturer:	Apple Inc.
  Location ID:	0x01000000

**Comment by imbushuo** [comment]
0x0291 is currently supported with both USB and SPI driver, depends on the actual configuration. Please try to install the new package and provide feedback.
