### ISSUE TITLE
MODEL SUPPORT REQUEST For MacBookPro15,2 (13" 2018 with Touchbar)

### ISSUE THREAD

**Issue by rbdej** [imbushuo/mac-precision-touchpad#193]
Hi, I'd like to submit my Macbook's details. Hope this helps on your work :)
P.S. I didn't find the Driver ID under SPI (mine's empty), I found it under the USB section in System Report app.

Model Name:	MacBook Pro 13" 2018 with Touch Bar
Model Identifier:	MacBookPro15,2
Processor Name:	Intel Core i5
Processor Speed:	2.3 GHz
Memory:	8 GB 2133 MHz LPDDR3
Graphics:	Intel Iris Plus Graphics 655 1536 MB

Apple Internal Keyboard / Trackpad:
  Product ID:	0x027b
  Vendor ID:	0x05ac (Apple Inc.)
  Version:	9.27
  Serial Number:	FM7827301XGJ3VXAS+WRN
  Speed:	Up to 480 Mb/sec
  Manufacturer:	Apple Inc.
  Location ID:	0x80500000 / 3
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0
  Built-In:	Yes

Screenshots:
<img width="863" alt="Screen Shot 2019-06-16 at 8 05 51 PM" src="https://user-images.githubusercontent.com/51877738/59563895-42a08b80-9072-11e9-9b58-95b5cbe2ff19.png">
<img width="698" alt="Screen Shot 2019-06-16 at 8 07 15 PM" src="https://user-images.githubusercontent.com/51877738/59563913-9a3ef700-9072-11e9-8f52-186bdff9f45d.png">
<img width="863" alt="Screen Shot 2019-06-16 at 8 11 24 PM" src="https://user-images.githubusercontent.com/51877738/59563934-f6a21680-9072-11e9-853c-7e87ea7fdb35.png">

**Comment by Uhucream** [comment]
I agree with you.
I can't use Windows 10 on BootCamp without it.

**Comment by imbushuo** [comment]
Work started on https://github.com/imbushuo/mac-precision-touchpad/tree/t2, you can keep an eye on it.

**Comment by rbdej** [comment]
Thank you imbushuo for the great work 😄. I'll go test this out around next month.

**Comment by imbushuo** [comment]
Supported as https://github.com/imbushuo/mac-precision-touchpad/releases/tag/1907-3539.
