### ISSUE TITLE
Logitech T651 support

### ISSUE THREAD

**Issue by ErwinMeulman** [imbushuo/mac-precision-touchpad#194]
Will it be possible to get it work with the Logitech T651 ?

Info
<img width="445" alt="Schermafbeelding 2019-06-20 om 17 27 41" src="https://user-images.githubusercontent.com/22874090/59862514-36267680-9383-11e9-8ac0-e221ad481d09.png">

https://github.com/torvalds/linux/blob/master/drivers/hid/hid-logitech-hidpp.c
https://www.fclose.com/linux-kernels/70057/hid-introduce-hidpp-a-module-to-handle-logitech-hid-devices-linux-3-18-17/
https://6xq.net/git/lars/lshidpp.git/plain/doc/logitech_hidpp_2.0_specification_draft_2012-06-04.pdf

**Comment by imbushuo** [comment]
Currently only Apple trackpad will be focused on. But technically speaking, any absolute position devices can be converted to PTP trackpad.
