### ISSUE TITLE
MacBook Pro 15" 2019  i9-9880H (MacBookPro15,1) HID ID

### ISSUE THREAD

**Issue by deanylev** [imbushuo/mac-precision-touchpad#195]
Product ID:	0x027c
Vendor ID:	0x05ac (Apple Inc.)

![image](https://user-images.githubusercontent.com/22049511/59961465-6739af00-951b-11e9-8795-afc40dcf6c03.png)

**Comment by imbushuo** [comment]
0x027c is supported with #198. Please note that this is a highly experimental one with a few significant bugs. I am currently tracking them in separate issues.
