### ISSUE TITLE
Two finger click option

### ISSUE THREAD

**Issue by MB3hel** [imbushuo/mac-precision-touchpad#197]
I am using this driver on my MacBook Air (13" early 2014). When i click the left mouse button with another finger on the trackpad it performs a right click. I have not seen this happen with other precision touchpads so I assume it has something to do with this driver. Is there a way to disable this behavior?

**Comment by JLIspace** [comment]
This is actually implemented into windows 10. You can change it in Settings>Devices>Touchpad>"right click using two fingers"
