### ISSUE TITLE
Request for MacBook Air (Retina, 13-inch, 2019) T2

### ISSUE THREAD

**Issue by uueaaaa** [imbushuo/mac-precision-touchpad#204]
<img width="863" alt="スクリーンショット 2019-07-25 2 53 14" src="https://user-images.githubusercontent.com/53273717/61817031-8dd76680-ae88-11e9-84d0-cecdd7bcfe67.png">

**Comment by imbushuo** [comment]
@uueaaaa Can you provide physical dimension (width and length) of the new MacBook Air trackpad?

**Comment by uueaaaa** [comment]
@imbushuo Thank you. width:120.5mm (or120mm?) length:82mm
![IMG_0094](https://user-images.githubusercontent.com/53273717/61834572-72358580-aeb3-11e9-8038-f0990537ff8c.jpg)
![IMG_0095](https://user-images.githubusercontent.com/53273717/61834577-73ff4900-aeb3-11e9-954c-77abd11fee10.jpg)

**Comment by imbushuo** [comment]
Supported as https://github.com/imbushuo/mac-precision-touchpad/releases/tag/1907-3539.
