### ISSUE TITLE
How to install mbp 2015

### ISSUE THREAD

**Issue by taisetna** [imbushuo/mac-precision-touchpad#207]
I installed recent released driver on my MBP 2015 by following the instruction of main page.
But I can't see nothing on the update driver list on the device manager panel.

Did I miss something?

**Comment by introconsulting** [comment]
Same for me, tried it a few times, nothing.

Followed the instructions perfectly everytime.

Please help.

**Comment by pengboby126** [comment]
Install **all the three drivers** in the package. I managed to install in this way for my MacBook Pro 2015-mid

**Comment by annabakhanova** [comment]
Installing all three from the package worked for me too (mid 2015 retina MacBook Pro)

**Comment by taisetna** [comment]
Thanks @introconsulting  @pengboby126  and @annabakhanova !!
It works now :D
