### ISSUE TITLE
model support request for MacBook Air (Retina, 13-inch, 2018) reopen

### ISSUE THREAD

**Issue by liustar2008** [imbushuo/mac-precision-touchpad#208]
The latest driver doesn't work on the machine.
MacBookAir8,1
Product ID： 0x027a
Vendor ID： 0x05ac（Apple Inc.）
ST Version： 9.13
The latest driver only support the 0x027d, not 0x027a. please check the driver. Thanks!

**Comment by imbushuo** [comment]
@liustar2008 See https://github.com/imbushuo/mac-precision-touchpad/releases/tag/1907-3540
