### ISSUE TITLE
Driver Code 10 Error on MacBookPro15,2 (Macbook Pro 2018 13")

### ISSUE THREAD

**Issue by rbdej** [imbushuo/mac-precision-touchpad#210]
Hey, Im currently typing this without a functioning trackpad on Bootcamp because after install the trackpad just stops working (although I actually know how to rollback the driver). I had just installed it using the latest driver released, but then Im getting this error:

I dont know what to do to install this properly so please send some help. Thanks again guys :D

![image](https://user-images.githubusercontent.com/51877738/62183235-f7290f00-b38b-11e9-88d8-d1e6ab3cccaa.png)

![image](https://user-images.githubusercontent.com/51877738/62183528-22602e00-b38d-11e9-815b-4acd2b8825db.png)

**Comment by imbushuo** [comment]
@rbdej Check https://github.com/imbushuo/mac-precision-touchpad/releases/tag/1907-3541

**Comment by rbdej** [comment]
> @rbdej Check https://github.com/imbushuo/mac-precision-touchpad/releases/tag/1907-3541

Ok ok, i'll test it again next week. Thanks for the full support 🙂
