### ISSUE TITLE
Macbook Pro 15 inch 2018 with Touchbar Device ID

### ISSUE THREAD

**Issue by sskye123** [imbushuo/mac-precision-touchpad#211]
Hi, I have tried many versions but they are not working for my MacBook. Here I posted my Device ID for your review. Thank you very much for your hard works.

USB type trackpad
Product ID:	0x027c
 Vendor ID:	0x05ac (Apple Inc.)

**Comment by imbushuo** [comment]
Use `AmtPtpDeviceUsbKm`. Have you turned off Secure Boot?
