### ISSUE TITLE
Not working on Macbook Pro14,3 (late-2017)

### ISSUE THREAD

**Issue by AlaricGilbert** [imbushuo/mac-precision-touchpad#213]
Not working on Macbook Pro14,3 (late-2017)
![image](https://user-images.githubusercontent.com/36405110/62595887-b9d7fa80-b912-11e9-8bdd-ea880e1519d3.png)
It says "One of the installers for this device cannot perform the installation at this time."

**Comment by AlaricGilbert** [comment]
Hey, I've noticed that your driver targets to Windows 10 1803 environment just now and my system version is 1903, is the installation error caused by system version not compatible?

**Comment by imbushuo** [comment]
@AlaricGilbert Drivers targeting 1803 works fine on 19H1. For MacBookPro14,3 you should follow the SPI installation guide as outlined in the README file.

**Comment by AlaricGilbert** [comment]
@imbushuo I'm sure that I followed the SPI installation instructions in the README file but the error occurs :(

**Comment by AlaricGilbert** [comment]
Update: I even tried to compile the driver myself in 1903 driver devkit and turned off sign-off verify, managed to get it installed but after installation nothing different to initial situation. QwQ.
I really want to be able to use it. Any solution?

**Comment by imbushuo** [comment]
@AlaricGilbert Check the SetupAPI log. The error message doesn't make sense to me either.

**Comment by AlaricGilbert** [comment]
Managed to get it working after reinstalled Windows.
