### ISSUE TITLE
BSOD on install of build 3544

### ISSUE THREAD

**Issue by cocowalla** [imbushuo/mac-precision-touchpad#214]
I have a 2017 MacBook Pro (14,2), and just tried installing the x64 SPI driver (which I assume is correct for the integrated trackpad?), but got a BSOD after right-clicking on the .inf file and selecting "Install".

Error code was `DRIVER_IRQL_NOT_LESS_OR_EQUAL`

```
==================================================
Dump File         : 081019-14250-01.dmp
Crash Time        : 10/08/2019 16:46:16
Bug Check String  : DRIVER_IRQL_NOT_LESS_OR_EQUAL
Bug Check Code    : 0x000000d1
Parameter 1       : 00000000`000000fe
Parameter 2       : 00000000`00000002
Parameter 3       : 00000000`00000000
Parameter 4       : fffff80f`89162640
Caused By Driver  : FT_Trackpad.sys
Caused By Address : FT_Trackpad.sys+2640
File Description  : MT_Trackpad Filter Driver
Product Name      : 
Company           : n/aa
File Version      : 2.0.0.0 built by: WinDDK
Processor         : x64
Crash Address     : ntoskrnl.exe+1aaab0
Stack Address 1   : 
Stack Address 2   : 
Stack Address 3   : 
Computer Name     : 
Full Path         : C:\WINDOWS\Minidump\081019-14250-01.dmp
Processors Count  : 4
Major Version     : 15
Minor Version     : 17134
Dump File Size    : 1,621,932
Dump File Time    : 10/08/2019 16:48:04
==================================================

```

HTML report from BlueScreenViewer is [here](https://gist.github.com/cocowalla/02499f5fb913552097a782aece2af427)

**Comment by imbushuo** [comment]
`MT_Trackpad Filter Driver` is not my driver - have you installed Trackpad++?

**Comment by cocowalla** [comment]
@imbushuo ah 对不起, as the BSOD happened on install of this driver, I presumed it was this driver that caused the BSOD!

I actually tried installing this driver because I find Trackpad++ really glitchy - better than Bootcamp's crappy Windows drivers sure, but still _very_ annoying!

I'll try uninstalling Trackpad++ first, and *then* installing your driver.
