### ISSUE TITLE
Can't init SDL DierctInput::CreateDevice: Device not registered

### ISSUE THREAD

**Issue by Goyadoy** [imbushuo/mac-precision-touchpad#215]
I have an issue with driver that results to crush Dosbox at startup with the following error:
Can't init SDL DierctInput :: CreateDevice: Device not registered

Aside of Dosbox I find that Crysis 2 is crushing at sturtup (with no error at all but I suppose because of the same reason), and Stalker Shadow of Chernobyl starts with no mouse pointer at all, so I have to navigate menu with keyboard to exit. I suspect that the precision driver is not detected by this apps, so they thinks that there is no mouse in the system at all. I don't know if this issue common for all precision drivers or if it is only for this driver. And I'd like to note that all this apps works correct if I roll back to original touchped driver.

My device is Macbook Pro 15 2017.

**Comment by imbushuo** [comment]
@Goyadoy I expect this because this PTP driver does not expose mouse device - won't fix at this moment but added for further consideration.
