### ISSUE TITLE
SPI Driver crashes on KabyLake 2017 MBP, when resuming from sleep.

### ISSUE THREAD

**Issue by TheEngineerGuy** [imbushuo/mac-precision-touchpad#220]
SPI Driver crashes on KabyLake MBP, when resuming from sleep.

Put MBP in sleep, resume from sleep, mouse driver will not work. Need to disable and re-enable device to get it working.

**Expected behavior**
Waking up from sleep driver should not crash.

**Environment**
MBP KabyLake, SPI driver, Win 10 x64 b1903.

**Comment by AuroraWright** [comment]
https://github.com/imbushuo/mac-precision-touchpad/issues/203

**Comment by imbushuo** [comment]
#203

**Comment by imbushuo** [comment]
BTW, that's a fail-out. If it crashes, you will see bugcheck/bluescreen. 😜
