### ISSUE TITLE
Windows Stops the Driver Because it "Malfunctions"

### ISSUE THREAD

**Issue by brandon-james105** [imbushuo/mac-precision-touchpad#222]
2016 MacBook Pro 15" (SPI)

When resuming from sleep, trackpad is unresponsive. Upon checking Device Manager there is a message noting that Windows shut it down due to its malfunction.

**Comment by imbushuo** [comment]
Duplicate of #203. Be careful with the test build under #203, it bugs the Apple bus driver.
