### ISSUE TITLE
Change four-finger to three-finger in switching between desktops?

### ISSUE THREAD

**Issue by kalatehbali** [imbushuo/mac-precision-touchpad#231]
Dear developer, 
I am so much thankful of your release.
I have a request and that is I would like to switch between desktops with three-finger instead of four-finger.
Is there any way to modify this?
Thanks.

**Comment by imbushuo** [comment]
![image](https://user-images.githubusercontent.com/6284353/67187281-dd5dfd80-f3b7-11e9-9458-6aa07c19e376.png)
