### ISSUE TITLE
Right/Left scroll with two fingers

### ISSUE THREAD

**Issue by kalatehbali** [imbushuo/mac-precision-touchpad#234]
I'm finding that I can't scroll left to right except by manually dragging the scroll bar at the bottom of the page in some applications. Is there no way to use my built-in Trackpad to scroll through the timeline or configure the application with this?

I have no problem with left/right scrolling in Notepad++.

**Comment by imbushuo** [comment]
That's really a Windows problem, so I suggest you to leave a feedback in the Feedback Hub too. I am afraid that what I can do is limited.
