### ISSUE TITLE
Caution: Uninstall Trackpad++ driver before installing this

### ISSUE THREAD

**Issue by vishal-ph** [imbushuo/mac-precision-touchpad#240]
If you have tried trackpad++ driver in the past on your PC and now want to switch to this driver then the information below is important.

Before, you install this driver it is crucial you uninstall trackpad++ app from program files and also the drivers from C:/Windows/System32/DriverStore. If you do not do this, you will lose your mouse pointer right after installation. To prevent this, make sure you have removed both the app and the drivers from trackpad++

**Comment by vishal-ph** [comment]
If you have tried trackpad++ driver in the past on your PC and now want to switch to this driver. Information below is important.

Before, you install this driver it is crucial you uninstall trackpad++ app from program files and also the drivers from C:/Windows/System32/DriverStore. If you do not do this, you will lose your mouse pointer right after installation. To prevent this, make sure you have removed both the app and the drivers from trackpad++

**Comment by imbushuo** [comment]
See also: https://github.com/imbushuo/mac-precision-touchpad/issues/214

**Comment by imbushuo** [comment]
This is a Trackpad++ issue, so what I can do is limited.

Pinned for further references.

**Comment by shudabi** [comment]
Sorry for my carelessness. I just did not uninstall trackpad++ before the installation and it turns out that my touchpad cannot work. Is there anyway to repair this？

**Comment by imbushuo** [comment]
@shudabi Use an alternate mouse to do a complete Trackpad++ driver removal. Then go to device manager, remove the trackpad device (also check remove driver package), rescan changes and reinstall the driver.

**Comment by shudabi** [comment]
It works!!! Thanks for your help.

**Comment by franciscobouza** [comment]
I made the mistake of installing TrackPad++ before hearing about this wonderful driver... I installed it while I had TrackPad++, then uninstalled TrackPad++ and tried installing this driver again... I don't see this working... Should I uninstall this driver and install it again?

**Comment by christinem** [comment]
> @shudabi Use an alternate mouse to do a complete Trackpad++ driver removal. Then go to device manager, remove the trackpad device (also check remove driver package), rescan changes and reinstall the driver.

This worked perfectly for me, Trackpad++ had an error when installing so I decided to just switch to this, and experienced the problem of my trackpad not working anymore. Following these instructions using an external mouse worked perfectly. Thanks!

**Comment by NightMachinary** [comment]
You need to add this in bold to the readme. It's very serious.

BTW, you do not need a mouse to uninstall the trackpad++ driver. It's possible with just the keyboard (play with the keys TAB, ALT, SPACE, ENTER, WINDOW to get the hang of it.)

**Comment by MateoKngs** [comment]
> @shudabi Use an alternate mouse to do a complete Trackpad++ driver removal. Then go to device manager, remove the trackpad device (also check remove driver package), rescan changes and reinstall the driver.

I have uninstalled the Trackpad++ app. But not able to remove the driver. I'm logged in as the admin user, and also I have tried removing from CMD, but still says access denied, or SYSTEM permission needed, or logged on user does not have ownership privileges. What the hell is this issue!

**Comment by MateoKngs** [comment]
> @shudabi Use an alternate mouse to do a complete Trackpad++ driver removal. Then go to device manager, remove the trackpad device (also check remove driver package), rescan changes and reinstall the driver.

I don't know how to thank you. First I installed your driver and my MacBook's screen went blue. Then I read that I must first delete Trackpad++'s driver. After hours of struggling to remove Trackpad++ driver(because of permissions' issues), I removed that and installed your driver. Then I lost my mouse pointer as you said(😅) and then I went to Device Manager and updated the touchpad driver and now everything's fine.

**Comment by shad-1** [comment]
If you read this thread wondering if it will work, here's my experience: 

- Went to settings, uninstalled both programs with "Trackpad++" in the name
- When I went to the above file location to double check, there was no Trackpad++ driver 
- Installed via chocolatey, ran the script

And immediately, it began working. This is much better!

**Comment by kychris** [comment]
@shad-1 yep! that works, thanks!

@imbushuo thank you so much for this incredible driver! so amazing!

**Comment by hfake35** [comment]
The Trackpad++ Driver in driverstore was somehow protected by Windows and impossible to delete. The free software driverstoreexplorer (also hosted at github) solved the problem for me. 

BTW Thanks for this nice software. I appreciate it.

**Comment by mehdirazavi** [comment]
completely mac trackpad experience on windows . thanks you a lot
