### ISSUE TITLE
CAN NOT USE IN GAME!!!

### ISSUE THREAD

**Issue by a200411044** [imbushuo/mac-precision-touchpad#246]
no respond on league of legends
pls help....

**Comment by a200411044** [comment]
the cursor can still move but cannot use left/right click or other function....

**Comment by carrottopadc** [comment]
When I used the drivers on my 15 inch, I had a similar problem. It appeared as though it would only do one action at a time when it was in full screen. Ie move, click, key press etc

**Comment by a200411044** [comment]
i have tried in windows mode and it didnt work too

**Comment by imbushuo** [comment]
Duplicate of https://github.com/imbushuo/mac-precision-touchpad/issues/206, I am currently aware of that. Discussion will be tracked there.
