### ISSUE TITLE
Magic Trackpad 2 on Surface Laptop 2

### ISSUE THREAD

**Issue by XingyuZU** [imbushuo/mac-precision-touchpad#247]
I want to use Magic Trackpad 2 on Surface Laptop2 (a windows laotop with touchpad)
I pair the Trackpad with the laptop using bluetooth firstly and I can use it as a mouse.
Then I run the step of "Converged Installation Guide" from 1 to 5, it tells "操作成功完成", but nothing changes, I don't know if the driver installed well and how to confirm it.
I want to get some suggestions about the steps to install the driver for Magic Trackpad 2 on a windows laotop with touchpad.

**Comment by imbushuo** [comment]
Bluetooth is not yet supported. Therefore you have to connect the trackpad via USB.
