### ISSUE TITLE
The third party inf does not contain digital signature information

### ISSUE THREAD

**Issue by mehdien** [imbushuo/mac-precision-touchpad#248]
hi guys, I am encountering a problem installing this driver, 
when i right click and install the amtptpdevice.inf on 

C:\Users\Mehdi\Downloads\mac-precision-touchpad-master\mac-precision-touchpad-master\src\AmtPtpDeviceUniversalPkg

i get this error message
The third party inf does not contain digital signature information

am i doing something wrong ?

MATERIAL
Macbook pro 2016 15 
windows 10 1863

![screenshot inf](https://user-images.githubusercontent.com/59016620/71096078-8d56a980-2162-11ea-8976-9ca005e71f54.png)

**Comment by mehdien** [comment]
Can someone please do a How to install video with all the steps starting from the download and post it somewhere on YouTube ?

**Comment by imbushuo** [comment]
You are downloading the source code. Please proceed to release section.
