### ISSUE TITLE
T2 chip disabled throughout install?

### ISSUE THREAD

**Issue by bradyankenbrandt** [imbushuo/mac-precision-touchpad#251]
Hi,

I admit this isn't a feature request, but more a question -- does the T2 chip have to remain disabled for the duration the driver is in use, or only during installation? No big deal either way, but I'm just curious. Likely going to install regardless considering how awful Trackpad++'s monetization+junkware is.

**Comment by imbushuo** [comment]
As long as your device is running, T2 is active. T2 is a multifunctional chip that acts as disk controller, HID relay (keyboard and trackpad), camera and misc services.
