### ISSUE TITLE
[resolved] can't find .inf file

### ISSUE THREAD

**Issue by airpods1** [imbushuo/mac-precision-touchpad#253]
Hello,
In any of the unzipped driver files I can't find AmtPtpDeviceUsbUm.inf. I don't know what driver to install

**Comment by dunestorm333** [comment]
Assuming you're on 64-bit version of Windows, you need to right click and install **AmtPtpDevice.inf** from the extrated path **Drivers\AmtPtpDeviceUniversalPkg\x64\ReleaseSigned\AmtPtpDeviceUniversalPkg**.

**Comment by airpods1** [comment]
I don't know if there's something I'm not seeing. 

![64 bit](https://user-images.githubusercontent.com/58206900/71855486-45112280-3135-11ea-8a23-3a101635dfa9.PNG)

![can't find inf](https://user-images.githubusercontent.com/58206900/71855487-45a9b900-3135-11ea-80fb-3c94c9906c6f.PNG)

**Comment by dunestorm333** [comment]
> I don't know if there's something I'm not seeing.
> 
> ![64 bit](https://user-images.githubusercontent.com/58206900/71855486-45112280-3135-11ea-8a23-3a101635dfa9.PNG)
> 
> ![can't find inf](https://user-images.githubusercontent.com/58206900/71855487-45a9b900-3135-11ea-80fb-3c94c9906c6f.PNG)

That's the one the second entry down, you need to right click and install it.

**Comment by airpods1** [comment]
I don't know what happened but now it's showing the correct .inf files. However, now when I try to right click I don't the option to install?

![can't install](https://user-images.githubusercontent.com/58206900/71859814-6cbbb700-3144-11ea-8590-2546b6e6e4c5.jpg)

**Comment by dunestorm333** [comment]
> I don't know what happened but now it's showing the correct .inf files. However, now when I try to right click I don't the option to install?
> 
> ![can't install](https://user-images.githubusercontent.com/58206900/71859814-6cbbb700-3144-11ea-8590-2546b6e6e4c5.jpg)

That's not right, there should be an option to install visible on INF files when right clicking them. Not sure where to go from here other than to try and find the correct trackpad device in device manager and install it from there.

**Comment by airpods1** [comment]
I haven't activated Windows (I'm current running the free version) so my limited access to a lot of features might be inhibiting things? Not sure.

**Comment by anuscleaner** [comment]
think u might be clicking the file while it's still in the zip file. try extracting it somewhere then right click, you should see the install option

**Comment by airpods1** [comment]
Yes, it works now! I wasn't extracting it but instead just opening the zip file. 
Thanks so much dunestorm33 and anuscleaner!
