### ISSUE TITLE
Can't turn Secure Boot back on...

### ISSUE THREAD

**Issue by slminneman** [imbushuo/mac-precision-touchpad#264]
So, I successfully installed the drivers on my MBP 16" running Windows 10 Pro.

As suggested, I had to turn Secure Boot off.  I was using old instructions and did the old TESTSIGNING step.

The drivers work fine, and I love all of the new functionality, but I can't turn Secure Boot back on.  If I select high security, it tell me I need to have network on for some reason, but there's no apparent way to do that.

If I select medium security, it'll allow that choice, and the subsequent boot has no trackpad pointer (if I Command-R and select no boot security, it comes back).

Any suggestions?  ...or is this expected behavior?

Thanks!  Scott

**Comment by imbushuo** [comment]
You need to turn off Secure Boot at now, but `TestSigning` is not necessary. You can let Windows to verify signatures and this will go through fine.

**Comment by slminneman** [comment]
But, like I said, the machine will not let me turn Secure Boot back on.  Do I have to leave it off permanently?

 

Thanks!

 

Scott

**Comment by imbushuo** [comment]
This will last for a while (at least a few more months), then the situation will be re-evaluated.

Thanks,
Bingxing (Ben) Wang
