### ISSUE TITLE
Touchpad failed after reboot on rMBP 2013.

### ISSUE THREAD

**Issue by leoleoasd** [imbushuo/mac-precision-touchpad#265]
**Describe the bug**
Must reinstall the inf file to use touchpad after reboot.

**Environment**
Win10, 1903, updated July.
rMBP, 2013, 13inch.

**Comment by imbushuo** [comment]
@leoleoasd Do you have a screenshot about failure details?

**Comment by leoleoasd** [comment]
> @leoleoasd Do you have a screenshot about failure details?

There aren't any visible error message and after a few reboots and reinstall the inf file the problem solved.
