### ISSUE TITLE
trackpad 2 bluetooth connectivity status

### ISSUE THREAD

**Issue by woshilaiba** [imbushuo/mac-precision-touchpad#266]
Hello, I used your usb driver for trackpad 2 on windows, and IT'S AWSOME !!!!!!
I have tracked the status of "trackpad 2 bluetooth connectivity" for about 1 month,
and today I find that it is closed, so i'd like to know if it is completed or not.
I really appreciate your work on  usb driver for trackpad 2 !!!
Thankyou very very much!

**Comment by imbushuo** [comment]
Not yet done. I am merging tickets right now so a few has been closed.

I expect it to be done before this quarter.
