### ISSUE TITLE
请问怎么重新装回原来的驱动

### ISSUE THREAD

**Issue by Jkdu** [imbushuo/mac-precision-touchpad#273]
不好意思，我英文不好，请问怎么装回原来的驱动，我装了驱动后发现电脑出了滋滋的电流声，是哪里出了问题

**Comment by Jamesits** [comment]
设备管理器里面找到设备卸载驱动然后重新安装 bootcamp 驱动即可。

**Comment by Jkdu** [comment]
![image](https://user-images.githubusercontent.com/62086841/76499549-e2f8d480-6479-11ea-9ff3-4f9d033cd9d8.jpg)
你好，我找不到，可以详细指导下吗，我不太懂这个

**Comment by Jamesits** [comment]
在人体学输入设备里面找一下

**Comment by Jkdu** [comment]
这个操作我搞不了。轻微的滋滋声是硬件问题还是驱动问题，把window系统删掉可以解决吗

**Comment by Jkdu** [comment]
打错字了，把window系统删掉可以解决吗

**Comment by Jamesits** [comment]
是硬件问题，请咨询 Apple 授权维修服务中心
