### ISSUE TITLE
Disable right click with two fingers pressing.

### ISSUE THREAD

**Issue by squalsoft** [imbushuo/mac-precision-touchpad#277]
**Pre-report checks**
- [x ] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Frequently when i click immediatelly after moving cursor i receive right click action.

**Comment by squalsoft** [comment]
By the way it exists some setting (in registry maybe) to disable right click on touchpad?

**Comment by squalsoft** [comment]
I found solution with AutoHotkey: 
RButton::LButton

**Comment by plainerman** [comment]
Assuming you are on Windows 10, you can change it in the normal precision driver settings.
Settings > Devices > Touchpad >[Taps] Tap with two fingers to right-click.

@imbushuo I believe this issue can be closed.

**Comment by squalsoft** [comment]
I talk about clicks not taps. So this can't be disabled in windows. But i close this issue because this problem is much deeper.
