### ISSUE TITLE
HI~

### ISSUE THREAD

**Issue by oTMaN-chengQ-G** [imbushuo/mac-precision-touchpad#281]
Hello, this is what I use translation software content, my English is very bad.
How does this tool allows windows laptop, support apple second generation of control panels wonderful it?

**Comment by Jamesits** [comment]
I'm sorry your translation software produced incomprehensible text. Could you please provide the text in your native language?

**Comment by imbushuo** [comment]
@oTMaN-chengQ-G Insert Magic Trackpad 2 via USB to Windows PC would make it work.
