### ISSUE TITLE
2020 MacBook Air Support

### ISSUE THREAD

**Issue by wahoofan5** [imbushuo/mac-precision-touchpad#286]
**Bug Description**
The latest AMD release doesn't appear to be working on the new 2020 MacBook Air with a T2 chip. I've disabled Secure Boot and tried installing the .INF file and, while the file says it installed successfully, there are no changes to the Trackpad behavior post-install.

**To Reproduce**
Disable Secure Boot, download latest release, install the .INF file.

**Comment by ringoz** [comment]
Have you found a solution?

**Comment by Confusingboat** [comment]
Can we reopen this issue? I'm seeing the same on my 2020 MacBook Air.
