### ISSUE TITLE
no "install" options when right-click the .inf file

### ISSUE THREAD

**Issue by YingChuanLiao** [imbushuo/mac-precision-touchpad#301]
Hello,
As title I am not able to execute the file. I googled for the answer and none of them works. 
Can everyone share the solution? Thanks

**Comment by Jamesits** [comment]
Could you please take a screenshot of what you see in the context menu?

**Comment by YingChuanLiao** [comment]
![Annotation 2020-05-13 085806](https://user-images.githubusercontent.com/30761309/81836132-e9e2a880-94f7-11ea-97a8-41f91f12a549.png)

**Comment by Jamesits** [comment]
Please first unzip (extract) all the files.

**Comment by YingChuanLiao** [comment]
works. Thanks
