### ISSUE TITLE
Include keyboard tweaks for macbook's integrated keyboard

### ISSUE THREAD

**Issue by ilazycat** [imbushuo/mac-precision-touchpad#304]
**Pre-report checks**
- [x] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Is your feature request related to a problem? Please describe.**

First of all, thank you for your great job creating this wonderful project. 

However, I found it very odd to use the integrated keyboard with MacBooks. Since the [default keyboard mapping](https://support.apple.com/en-us/HT202676) which map command to windows, option to alt and no application key is quite different from standard windows keyboards. So I ran into issue which constantly press the wrong key. 

**Describe the solution you'd like**

I wonder whether it is possible to integrate or create a standalone keyboard driver for apple keyboards, which provide a more common key mapping. 

If it is possible, I'd like it to be
left ctrl -> left ctrl
left option -> left windows key
left command -> left alt
right command -> right alt
right option -> application
delete -> backspace

and if possible

fn + delete -> delete
fn + ↑ -> page up
fn + ↓ -> page down
fn + ← -> home
fn + → -> end

**Describe alternatives you've considered**

I've tried using SharpKeys and other key remapping applications. Even tried registry hack. But they simply can't map key for a per-keyboard basis. So each time I plug or unplug an external keyboard, I have to logoff or reboot otherwise the key mapping fo keyboard will be wrong.

I haven't try create custom keyboard layout since it seems that keyboard layout cannot set win key and application key. And it still requires manually switch when changing keyboards. And I think it might be quite difficult to work with some input methods.

For now I use SharpKeys to change the key mappings, and luckily my external keyboard (CoolMaster MK750) that I use at work support changing key mappings from it's driver. But the problem persists when I use other keyboards which doesn't support such functionality. 

**Additional context**

I found [WinAppleKey](https://github.com/samartzidis/WinAppleKey) on GitHub which might be useful.

Thank you very much.

**Comment by imbushuo** [comment]
Keyboard is a separate device from the view of OS. It might be feasible to start a new project for such enhancement, but this is out of the scope of trackpad driver.
