### ISSUE TITLE
Reverse Horizontal scrolling optionally w/o reversing vertical

### ISSUE THREAD

**Issue by rbreaves** [imbushuo/mac-precision-touchpad#307]
**Pre-report checks**
- [x] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Is your feature request related to a problem? Please describe.**
Not really, I think it behaves as intended.

**Describe the solution you'd like**
I'd like a way to enable reversed horizontal scrolling, particularly or only on the 3 finger gesture motion. It makes more intuitive sense to me personally as nothing but the content of the screen is shown whereas vertical scroll bars are the item I feel like I am manipulating, not the content of the screen.

**Describe alternatives you've considered**
I've tried many registry keys that looked promissing FlipFlopHScroll type stuff and reboots, but it led to nothing different. Also looked at what the Left and Right 3 finger gestures where actually binding to in the registry thinking maybe I could just swap their values out, but they share the same value of 4 in my case (changing virtual desktops).

**Comment by imbushuo** [comment]
Since we are implementing Windows PTP device, it is not possible to implement such without Microsoft implementation. Please file a suggestion in the feedback hub.
