### ISSUE TITLE
Causes max payne 3 to crash on launch

### ISSUE THREAD

**Issue by georgesunnyt** [imbushuo/mac-precision-touchpad#309]
Description
This driver causes Max payne 3 to not launch. It starts with a black screen and exits without any error when this driver is installed

Start max payne 3 with this driver installed

Device: macbook pro mid 2017 with AMD Radeon pro 560 
Os : macOs catalina 10.15.5
Bootcamp os : windows 1909
Touchpad drivers for SPI

Swiching to apple original drivers allows game to launch again.

**Comment by imbushuo** [comment]
I would say it is looking for a mouse device and failed to find one. There will be some basic mouse support in long-term but not on the top priority right now.

**Comment by imbushuo** [comment]
Merge into #206
