### ISSUE TITLE
These drivers break some UDK games.

### ISSUE THREAD

**Issue by jespertheend** [imbushuo/mac-precision-touchpad#311]
Not sure if this is something that can be fixed by these drivers, or if this is something that needs to change on epic games' end. But I wanted to mention this anyway since it might save someone else some time.

Some older UDK based games crash after the splash screen with this driver installed.
Some games simply crash and only show "filename not found with a memory address in the log. But one (Q.U.B.E. Directors cut in particular) showed some more info that might be useful:

```
Assertion failed: SUCCEEDED( DirectInput8->CreateDevice(GUID_SysMouse, &DirectInput8Mouse, NULL ) )
[File:F:\Projects\QUBE-UE3\trunk\Development\Src\WinDrv\Src\WinClient.cpp] [Line: 414]

Stack Address = 0x963299  (filename not found) [in C:\Program Files(x86)\Steam\steamapps\common\QUBE Directors Cut\Binaries\Win32\QUBEGame.exe]
```

I haven't found a temporary workaround for this. (I was hoping for some windows 10 compatibility settings or something).
In order to play these games you have to completely uninstall the drivers and restart the computer. Disabling the device in device manager is not enough unfortunately.

**Comment by imbushuo** [comment]
Dup of #309
