### ISSUE TITLE
Compatibility with Windows 7

### ISSUE THREAD

**Issue by MENovello** [imbushuo/mac-precision-touchpad#314]
Please, the driver is compatible with Windows 7? I did the following steps with the follwing erros:

- Install the certificate (ok)
- bcdedit -set TESTSIGNING ON (ok)
- Tried to install the driver with a right click/install over the inf file. (error: "The INF file you selected does not support this method of installation"
- Tried to install the driver on the Device Manager (HID > Apple Multitouch Mouse > Install new driver with disk > (error: "Windows encountered a problem installing the driver software for your device" ... name of the drive... The parameter is incorrect"  
I tried with the versions 3826, 3805, 2358, 2802, 1806, M4, and allways the same error.

Macbook air 11 mid 2012
Windows 7 x64

Many thanks
![error](https://user-images.githubusercontent.com/67391331/85621901-65c62980-b63c-11ea-8eed-22c936972edf.PNG)

**Comment by imbushuo** [comment]
Windows 7 don't have Precision Touchpad support. This is a Windows 8.1+ feature.

Additionally, this driver targets Windows 10 DDI so I cannot guarantee that it even works on Windows 7.
