### ISSUE TITLE
MacBook Pro 2017

### ISSUE THREAD

**Issue by PaulWen** [imbushuo/mac-precision-touchpad#33]
Hi, thank you for your great work!!
I am really interested in a precision touchpad driver for the MacBook Pro 2017. Can you tell me if/when this model will be supported?

**Comment by imbushuo** [comment]
Planned. New models use SPI-only trackpad, which needs additional research.

**Comment by PaulWen** [comment]
Thank you @imbushuo. I just came across the following Git repo: [https://github.com/cb22/macbook12-spi-driver](url). Unfortunately, I am not able to evaluate if it helps regarding the SPI topic. But in case you have not seen it yet I wanted to point it out.

**Comment by PaulWen** [comment]
If I understood Microsoft's documentation correctly an SPB Framework exists for developing SPI drivers. The SPB Framework is a KMDF extension library. It seems like a KMDF driver instead of a UMDF driver has to be written in order to support an SPI device.

> The SPB Framework Extension is a KMDF extension library. It handles the up-front processing of SPB request and the sequence in which they are handed to the controller driver. The SPB framework extension is designed to support I²C and SPI buses and may be appropriate for other buses with similar semantics. 
[(source)](https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/simple-peripheral-bus--spb-)


An introduction to the SPB framework can be found [here](https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/simple-peripheral-bus--spb-#spb-framework-extension).

**Comment by tspitznas** [comment]
It will make my life infinitely better if or when you are able to get compatibility with MacBookPro13/14,3 SPI models. Keep up the fantastic work!

**Comment by jourdant** [comment]
Hi @imbushuo really appreciate the work you are putting in - do you any updates on progress?

**Comment by imbushuo** [comment]
See #ee.
