### ISSUE TITLE
request 3-finger drag feature.

### ISSUE THREAD

**Issue by ShinChven** [imbushuo/mac-precision-touchpad#333]
Thanks for your work, you did a great job to port the driver to Windows.

Hope it implements the 3-finger drag feature.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement the 3-finger drag feature.

**Additional context**
Please search `3 finger drag` in [this page](https://support.apple.com/en-us/HT204895), if you haven't use it before.

**Comment by imbushuo** [comment]
Tracked in https://aka.ms/AA92oyn

**Comment by VICLER** [comment]
Ist this feature now implemented? 
That is only one thing that I miss in this wonderful Driver.

**Comment by ShinChven** [comment]
> Ist this feature now implemented?
> That is only one thing that I miss in this wonderful Driver.

Last week I checked: no.

**Comment by VICLER** [comment]
@imbushuo please implement this feature. With 3 finger drag I can completely replace my mouse with a trackpad. It is very usefull and comfortable! Thank you very much!
