### ISSUE TITLE
Windows Pro N not detected as a supported OS

### ISSUE THREAD

**Issue by dxu** [imbushuo/mac-precision-touchpad#338]
**Pre-report checks**

- [x] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Describe the bug**

When installing on Windows Pro N x64, the installation fails with "ERROR: Cannot be installed on this version of Windows. Requires Windows 10 x64."

**To Reproduce**

run installation on admin shell

**Expected behavior**

I expected it to be installed

**Traces**
If applicable, add WPP traces to help explain your problem.

**Environment**
Add your device model, driver type (USB or SPI) and OS version here.

Windows Pro N, x64

**Comment by imbushuo** [comment]
Hmm, Windows 10 Pro N? We don't support 8.1 N or whatever due to licensing reasons.
