### ISSUE TITLE
Consistent release asset naming

### ISSUE THREAD

**Issue by pauby** [imbushuo/mac-precision-touchpad#356]
**Pre-report checks**

- [X] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Describe the bug**
The release assets were named `Drivers-a....` in previous releases but named `Driver-a...` in this latest release (note the missing **s** at the end of Driver).

**Expected behavior**
The release assets to be consistently named. This makes it easier for the Chocolatey package (which detects the latest version by checking the release name) and probably others to determine new versions.

Thanks!

**Comment by imbushuo** [comment]
@pauby fixed.
