### ISSUE TITLE
Not work on macbook 12’ 2015?

### ISSUE THREAD

**Issue by duanyu47** [imbushuo/mac-precision-touchpad#36]
Precision Touchpad option does not shown after installing driver on my macbook2015（MacBook 8？）

**Comment by imbushuo** [comment]
See #33. I have just started some early research with SPI-only models (MacBook Pro 13-inch 2015, 13/15 2016, 2017, MacBook 2015, 2016), and I will get a SPI-only model MacBook later to do some experiments. 

Have to look into product IDs for the accuracy of README.md.

**Comment by duanyu47** [comment]
那应该是描述文件写错了……MacBook8是2015款12寸的产品ID，MacBook1-7才是以前老款塑料外壳MacBook

https://everymac.com/ultimate-mac-lookup/?search_keywords=MacBook8,1

**Comment by imbushuo** [comment]
See #36.

**Comment by imbushuo** [comment]
@duanyu47 Can you report your MacBook (12-inch, 2015)'s SPI device model so I can add model entry in driver INF file?
