### ISSUE TITLE
Middle mouse button click on three-finger tap instead of start menu

### ISSUE THREAD

**Issue by flying-sausages** [imbushuo/mac-precision-touchpad#361]
**Pre-report checks**
- [x] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Is your feature request related to a problem? Please describe.**
I would like to use the three-finger tap/click gesture as the middle mouse button click. It's super sweet to open links in new tabs with it instead of holding control down. Currently, having it trigger the Start menu makes little sense to me.

It would make most sense to have 1-finger be MOUSE1, 2 finger be MOUSE2, and 3 finger be MOUSE3.

**Describe the solution you'd like**
When three-finger tap/click occurs, trigger middle mouse button event.

**Describe alternatives you've considered**
Trackpad++ has this but those drivers are cursed

**Additional context**
I'm sure your girlfriend will appreciate the three-finger action.

**Comment by bcat** [comment]
This is already available as a standard Windows feature: https://www.nextofwindows.com/windows-10-tip-how-to-simulate-a-middle-button-on-a-touchpad
