### ISSUE TITLE
How do I revert back to the original Apple driver?

### ISSUE THREAD

**Issue by NightMachinary** [imbushuo/mac-precision-touchpad#365]
Uninstalling "Apple SPI Precision Touchpad Device" disables the trackpad completely, and scanning for new hardware does not fix it. I also don't have the Bootcamp installation files.

![image](https://user-images.githubusercontent.com/36224762/98021626-c26ef780-1e19-11eb-919e-d54b591e9427.png)

**Comment by imbushuo** [comment]
Uninstall this needs an alternate input device (keyboard if you familar) or another mouse. When removing the device you also need to specify uninstalling drivers.
