### ISSUE TITLE
Trackpad will ask for a pin to connect that is: 0000

### ISSUE THREAD

**Issue by ant6969** [imbushuo/mac-precision-touchpad#366]
I suggest that you include this in the explanation: 
Trackpad will ask for a pin to connect, and the PIN is: 0000

**Pre-report checks**
- [ ] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imbushuo** [comment]
We don't pushed Bluetooth yet. But this will be tracked.
