### ISSUE TITLE
Two finger scroll and tap to click randomly stops working under Chromium browsers.

### ISSUE THREAD

**Issue by builtinhold** [imbushuo/mac-precision-touchpad#367]
**Pre-report checks**

- [x ] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Describe the bug**
Tap-to-click and two ginder scroll stops working in an random way under chromium base browsers. It is happening under Edge and Chrome. When several tabs are active, randomly the scroll while browsing and tap to click will stop working. Alt+tab to other applications prooves that the two finger scroll is correctly identified by other applications. Tap to click however, is not for the duration of this glitch. Eventually, after about 20-40 seconds both gestures start working correctly inside and outside the browser.
I removed every extension, cleaned up both browsers. It never happened with the stock bootcamp driver, or in any other application outside the browsers. Smooth scrolling flag in the browsers is set to Default.

**To Reproduce**
Open a few times in chrome/edge. It occurs about 2-3 times per hour.

**Expected behavior**
Tap-to-click and two finger scroll working in a stable manner.

**Traces**
Not sure how to get these. Happy to spend some time with it if someone can point me in the right direction.

**Environment**
MacBook Pro 13 2020 , i7-1068NG7, Windows 10 Pro 2004
Driver release 3835

**Comment by imbushuo** [comment]
I am aware of this issue and has various repro on Edge and Chrome with several devices, so I believe this should be Chrome's issue.
