### ISSUE TITLE
Ability to change horizontal scroll speed

### ISSUE THREAD

**Issue by jimfarms13** [imbushuo/mac-precision-touchpad#373]
Some creative applications, such as Ableton Live, rely on the "choose how many lines to scroll each time" setting in the mouse settings in Windows (not touchpad settings) to change the scrolling speed of the touchpad. However, this setting only changes the vertical scrolling speed, which is a problem in a lot of creative applications, where horizontal scrolling is required as well. This means that the horizontal scrolling in these applications is annoyingly slow and unchangeable. 

A setting that alters the horizontal scrolling speed as well as vertical scrolling speed would be greatly appreciated.

I am on a 16-inch Macbook Pro 2019

**Comment by Cyberdroid1** [comment]
I think this is a feature request for Windows settings, and not driver related. Do file a feedback on Feedback Hub for the same.
