### ISSUE TITLE
support for Win 10 as Virtual Machine Manager VM Guest on Fedora

### ISSUE THREAD

**Issue by droddy** [imbushuo/mac-precision-touchpad#380]
I'm running Win10 as a virtual machine on Fedora 33 (Linux). I'm guessing there is some issue with the communication from Linux to the VM. I'm able to use the trackpad but after installing the the .inf on Windows, there is no Touchpad settings control panel

**Comment by imbushuo** [comment]
Yes, that's intended because the USB device is not passed in. We only support bare-metal scenarios yet (or if wish to pass the whole USB device at the risk of losing input device for the host)
