### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by lfrohling** [imbushuo/mac-precision-touchpad#386]
This might sound like a silly question but it's a genuine one. I've seen lots of GitHub related pages and those which don't have a clearly specified zip/exe to download in the main directory always require some sort of specific knowledge usually targeted to the type of software/hardware. 

I'm a generalist and usually need fixes for different hardware/software problems (one day it's trackpad for Windows 10 drivers and the next it's flashing ROM's on DVD players) and hence really value clearly written readme's which don't assume the reader knows how to assemble a build for that specific hardware/software.

Sorry to sound ungrateful (which I'm REALLY not- so many manufacturers' expect everyone to bend to their will instead of providing the tools to customize their equipment to suit the customers- it's up to the dedicated/elite/fans/bored to build said tools) but would you mind including the missing "for dummies" first steps please? ie. which files to download, providing a self-executable build for a GUI, etc please?

Thank you :)
Luke

**Comment by JohnRThomas** [comment]
Hey!

If you go to the main github page for this project and scroll down a bit there are installation instructions. They say:
1. Make sure you uninstalled Trackpad++ completely if you have previously does so
2. Go to the release tab in Github and download the newest version for your architecture (https://github.com/imbushuo/mac-precision-touchpad/releases)
3. Right click AmtPtpDevice.inf and install it

Have a nice day.
