### ISSUE TITLE
can not install the inf file on windows 10

### ISSUE THREAD

**Issue by evolfish** [imbushuo/mac-precision-touchpad#394]
I'm not sure why I can not right click the "install" on the inf file. I can only right click the "Open" and the file would be open as text file in Notepad.
I'm on 2019 macbook pro 16" and installed windows 10.
does anyone have the same issue?

**Comment by Naozumi520** [comment]
Try to install the inf file in Device manager: 
Open the "Human Interface Devices" slots and right click the "Apple Multi-Touch" device, click update driver, 
"Browse my computer for driver", "Let me pick from a list of available drivers on my computer", 
click "Have Disk", "Browse" and pick your inf file. Press ok and click "Next", then you should have the driver installed.
![image](https://user-images.githubusercontent.com/52615455/120093086-af30bb80-c0cc-11eb-99fe-fb6ec9fa0a36.png)

**Comment by evolfish** [comment]
@Naozumi520 
Thanks for your solution!
However, I don't know why I still encountered problems...
![Screenshot 2021-05-30 210205](https://user-images.githubusercontent.com/25810609/120105178-6b03f080-c18a-11eb-9bb1-f67204ff52c5.png)

**Comment by Naozumi520** [comment]
Hmmm, how about put the inf file in other places?

**Comment by Naozumi520** [comment]
This may cause by the file path name is too long.

**Comment by evolfish** [comment]
I pull the file to the download file. This should not be the problem (~_~)

**Comment by imbushuo** [comment]
Mind sending setupapi.dev.log to me? Should be relocated at Windows\Inf.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abulka** [comment]
I had the same problem - it turns out that I was browsing inside the `.zip` file via windows explorer's ability to navigate inside zip files - **but the zip file was not truly extracted to disk**. 

As soon as I properly unzipped the zip, I could right click on the extracted `.inf` file and `install` was now an option.
