### ISSUE TITLE
Extra character with 3 tap middle click paste action.

### ISSUE THREAD

**Issue by askhubbar** [imbushuo/mac-precision-touchpad#400]
1) connected to linux server using NoMachine from windows 10.
2) After selecting text, when performing 3 finger tap action to paste on linux terminal, extra character '~' is  added at the begining.
e.g:
text selected : command
After 3 finger tap on command line
user@machine/>~command

**Comment by imbushuo** [comment]
This looks like an issue not owned by us, but Windows or something else.
