### ISSUE TITLE
I can not uninstall driver

### ISSUE THREAD

**Issue by mehmetalier93** [imbushuo/mac-precision-touchpad#401]
Hi, I can not see "Apple SPI Precision Toucpad" line, by the way I can not unintall the driver. Please help.

![2021-06-03_17-51-11](https://user-images.githubusercontent.com/6951055/120665362-5f6b3f00-c494-11eb-9a52-d2fcc5b2301d.png)

**Comment by freecodecampster** [comment]
Try https://github.com/lostindark/DriverStoreExplorer

**Comment by mehmetalier93** [comment]
> Try https://github.com/lostindark/DriverStoreExplorer
> 
> ![Screenshot 2021-06-03 161649](https://user-images.githubusercontent.com/28160999/120669392-51fb8800-c487-11eb-82d1-adf1105ba3f0.jpg)

Thank you very very much 👍

**Comment by mvereecken** [comment]
Thanks a lot! This also fixed my problem! (I couldn't connect via bluetooth)
