### ISSUE TITLE
Questions on Hardware/Firmware

### ISSUE THREAD

**Issue by GeorgeLuther** [imbushuo/mac-precision-touchpad#404]
- is the magic trackpad 2 itself theoretically able to send 5 finger data for gestures?
- do es each finger send it's own xy up to 4 fingers?
- were you working on a GUI? Is it still in the works?
- what books, resources, courses, and starter projects should I explore to better understand your code and work with firmware and hardware in general 

- this is so awesome. It makes my days much more ergonomic. thanks!

**Comment by imbushuo** [comment]
> is the magic trackpad 2 itself theoretically able to send 5 finger data for gestures?
It supports at least 10 (and should be 16.) Windows PTP only wants at most 5 fingers, so I capped it.

> does each finger send it's own xy up to 4 fingers?
No. But the trackpad uses absolute coordinates, so this can be easily calculated.

> were you working on a GUI? Is it still in the works?
Work restarts recently: https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/edit/640

> what books, resources, courses, and starter projects should I explore to better understand your code and work with firmware and hardware in general
https://github.com/microsoft/Windows-driver-samples is a great place to go. Some basic required skills including C programming, some basic knowledge on USB, Bluetooth and HID. Most stuffs should be easily retrieved via Internet search.

> this is so awesome. It makes my days much more ergonomic. thanks!
Thank you for using my driver!
