### ISSUE TITLE
Can these drivers be used on Intel PCs? 

### ISSUE THREAD

**Issue by getify** [imbushuo/mac-precision-touchpad#408]
Apologies if there's an obvious yes/no here I've missed. I have a surface laptop with intel cpu and windows 10. Unclear if/how to use these drivers in that scenario? Any guidance is appreciated.

[AB#717](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/717)

**Comment by imbushuo** [comment]
Yes. It is not restricted to Mac :)

![image](https://user-images.githubusercontent.com/6284353/121821874-aacddc00-cc50-11eb-8b98-5c633bbefb66.png)

**Comment by getify** [comment]
What I'm confused about is that the driver files listed here on github are named "arm" and "amd"... neither of which seem correct for an Intel system.

**Comment by imbushuo** [comment]
@getify Intel EM64T is technically amd64, or called x64, so I am just using the build system convention there.
