### ISSUE TITLE
Phantom scroll

### ISSUE THREAD

**Issue by jjoshrtca** [imbushuo/mac-precision-touchpad#410]
**Pre-report checks**

- [x] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?  Yes

**Describe the bug**
Hard to describe, but the two finger scroll gesture sticks around after scrolling is done and fingers are lifted off the tp.  This causes problems, e.g., in Chrome, this zooms out (or in, I guess, depending on how you have your natural scroll setup -- I have mine set to scroll down when my fingers move down for sake of consistency because it mirrors actual mouse behavior for the times when I need to use a mouse).

**To Reproduce**
Scroll, release, then immediately hit ctrl (like you're scrolling to the bottom to copy paste).  Easiest to see in Chrome where scroll+ctrl is zoom.

**Expected behavior**
I expect the scroll gesture to be gone when I lift my fingers off the tp.  I think this may be related to a lot of other issues like mouse jumping and hovering.  Maybe increased filtering/lowered sensitivity would help a lot.  

**Traces**
If applicable, add WPP traces to help explain your problem.
N/A

**Environment**
Add your device model, driver type (USB or SPI) and OS version here.
Dell Inspiron 15 5000, USB w/ latest driver, Windows 10 (latest version/updates).

[AB#720](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/720)

**Comment by jjoshrtca** [comment]
Oh, forgot to mention that I think this may be due to the fog/condensation theory I mentioned in another issue about hovering/jumping.

**Comment by imbushuo** [comment]
Redirect to feature #405
