### ISSUE TITLE
Intermittent lack of movement if on ball of finger

### ISSUE THREAD

**Issue by jjoshrtca** [imbushuo/mac-precision-touchpad#411]
**Pre-report checks**

- [x ] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?  Yes

**Describe the bug**
The mouse cursor will not move if you transition from the tip of your finger to the ball/pad of your finger.  This is especially the case if on the edge of the trackpad.

**To Reproduce**
While moving the mouse, flatten your finger to try and move the cursor in any direction using the ball/pad of your finger (like you're trying to get the cursor to move just one cell down in Excel/spreadsheet).

**Expected behavior**
I expect the mouse to move, albeit more slowly/precisely.

**Traces**
If applicable, add WPP traces to help explain your problem.
N/A

**Environment**
Add your device model, driver type (USB or SPI) and OS version here.
Dell Inspiron 15 5000, USB (latest driver), Windows 10 (latest version/updates)

[AB#722](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/722)

**Comment by imbushuo** [comment]
Redirect to feature #405
