### ISSUE TITLE
Please create a Audio driver for Macbook Pro 16 Bootcamp Feature Request 

### ISSUE THREAD

**Issue by albertputinjobs** [imbushuo/mac-precision-touchpad#416]
Apple provided audio driver appleaudio.sys file is causing BSODs and is very unstable. I request you to provide audio drivers.

[AB#729](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/729)

**Comment by imbushuo** [comment]
That's out of the scope for this project.
