### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by zakhaj** [imbushuo/mac-precision-touchpad#42]
apologies if this might seem stupid.
cant install the .inf file on MBPr late 2012 10,2
repeatedly get warning of 'digital signature information'
have I missed a step?
attempted to update touchpad driver via device manager - doesn't recognise .inf file as appropriate driver...

have been eagerly awaiting a precision driver for bootcamp. long overdue!

**Comment by montajd** [comment]
you need to install the certificate included in the zip. Click on it and choose manual install, and choose trusted root

**Comment by zakhaj** [comment]
thanks for replying. where is it exactly? looked through everything, cant see what you mean?

**Comment by zakhaj** [comment]
there's no .cer file in my zip....?

**Comment by montajd** [comment]
Drivers.2014\Drivers\x64(or whatever your architecture)\ReleaseSigned\AmtPtpDevice.cer

**Comment by zakhaj** [comment]
inside my zip I see:

**Comment by zakhaj** [comment]
<img width="515" alt="capture" src="https://user-images.githubusercontent.com/35434107/34921508-7fe29eca-f951-11e7-93d1-9c80cabf7632.PNG">

**Comment by montajd** [comment]
that's the source, you need to download the actual release. 
https://github.com/imbushuo/mac-precision-touchpad/releases

**Comment by imbushuo** [comment]
Directly install inf file from GitHub release should be fine (with a publisher confirmation).
