### ISSUE TITLE
Detailed uninstall instructions for latest release 29

### ISSUE THREAD

**Issue by MagicUtilities** [imbushuo/mac-precision-touchpad#421]
The uninstall instructions are not up to date any more. We created a detailed help page on how to uninstall this driver for the Magic Trackpad 2 on USB and Bluetooth connections. 

[https://magicutilities.net/magic-trackpad/help/mac-precision-touchpad-driver-installed](https://magicutilities.net/magic-trackpad/help/mac-precision-touchpad-driver-installed)

You might consider to add this link to your uninstall instructions on the README.md page.

[AB#738](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/738)

**Comment by imbushuo** [comment]
Thanks! Updated the instruction text and link.
