### ISSUE TITLE
Touchpad settings not showing in Windows Devices settings when connected via bluetooth, but does show with wired connection

### ISSUE THREAD

**Issue by j9108c** [imbushuo/mac-precision-touchpad#425]
**Pre-report checks**
- [x] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Describe the bug**
Touchpad settings not showing in Windows Devices settings when connected via bluetooth, but does show with wired connection

**To Reproduce**
Steps to reproduce the behavior: install latest release −> pair magic trackpad 2 to pc −> go to Windows Settings −> Devices

**Expected behavior**
should show Touchpad settings since it should be Precision compatible now

**Environment**
- device: magic trackpad 2
- OS: windows 10 pro v=21H1 b=19043.1110

[AB#745](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/745)

**Comment by imbushuo** [comment]
You might have the same issue with this one: https://github.com/imbushuo/mac-precision-touchpad/issues/412
