### ISSUE TITLE
Question - Are there settings available in Windows 10 for Apple Trackpad 2

### ISSUE THREAD

**Issue by stephen147** [imbushuo/mac-precision-touchpad#429]
I saw this article here: https://techzoneonline.com/how-to-use-apple-magic-trackpad-2-on-windows-10/ that shows the settings below.

Do I get these settings available when the device is connected?

![image](https://user-images.githubusercontent.com/14054664/128767915-74492b64-b12a-40d9-8bf6-7874a97ba972.png)

[AB#752](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/752)

**Comment by lloydo3000** [comment]
Yes

**Comment by stephen147** [comment]
> Yes

Thank you. That's a great help. I was looking at this https://magicutilities.net/magic-trackpad/features but it's 10eur a year for a driver! I don't know if there are more settings available with that but I'll try this out when I go buy it.

These are the settings for that.
![image](https://user-images.githubusercontent.com/14054664/128778895-32710db9-4c26-4489-880d-043d7ec55d56.png)

**Comment by imbushuo** [comment]
As other answered, yes (all PTP trackpad will have that)

**Comment by stephen147** [comment]
Thanks for letting me know. So most of the options that are available with that magic utility app will be in this driver?

**Comment by lloydo3000** [comment]
Everything from the Windows settings page for Precision touchpads will be there. Let us know if you need a screenshot

**Comment by stephen147** [comment]
Yes, that would be great of you. Thanks.

**Comment by lloydo3000** [comment]
![image](https://user-images.githubusercontent.com/75959478/129729101-6c14b19c-028f-4038-b362-ba47dc61dff4.png)

**Comment by stephen147** [comment]
Thank you. It seems to have all the important features that the app at 10 eur a year has.
