### ISSUE TITLE
Windows11可以使用嘛？

### ISSUE THREAD

**Issue by adenm1** [imbushuo/mac-precision-touchpad#433]
Can I use this plug-in under Windows 11? My version is windows 11 professional 64 bit 22000

[AB#759](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/759)

**Comment by yaticl** [comment]
I have used this driver with Magic Trackpad 2 in Windows 11 for a while. Currently, it works as expected.

**Comment by sgzman** [comment]
I just installed it in win11 22454.1000，and it works

**Comment by imbushuo** [comment]
Yes
