### ISSUE TITLE
Windows 10 Bluetooth unable to find Apple Magic Trackpad 2

### ISSUE THREAD

**Issue by ProjectWP** [imbushuo/mac-precision-touchpad#444]
As the title says, for some reason, I am unable to "find" the apple magic trackpad 2 on windows 10 bluetooth settings, therefore unable to connect via bluetooth.

Please could you assist me, I love the driver, however medically I need the Bluetooth feature for my arm position. Thank you in advance!

[AB#771](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/771)

**Comment by imbushuo** [comment]
That might be Bluetooth controller's issue - which the driver cannot control.
