### ISSUE TITLE
Windows 11 Support..

### ISSUE THREAD

**Issue by drpalli** [imbushuo/mac-precision-touchpad#445]
Tried Installing it on windows 11 but the install button wouldn't appear on right-click. Only the open button appears and when clicked asks to run and after I click run, it does nothing.

Any Solution.?

[AB#773](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/773)

**Comment by MilkiiJugs** [comment]
> 
> 
> > If you choose "Show more options" that will show up. I just installed it on Windows 11 and it seems fine so far.
> 
> Could you please guide me through the installation process? If it works for you and doesn't for me, I must be doing something wrong. I use a mid-2015 13 inch MacBook Pro. It just opens the Notepad for me when I click open on the setup information file.

Simply pressing Show more Options at the bottom of the context menu, or if you rather, press Shift + F10 (if on MacBook, you may also need to hold down the fn or function button)

**Comment by cassius425** [comment]
It  also doesn't work for me  .  It was no response

**Comment by drpalli** [comment]
Hey Cassius, install it using chocolatey and it installs just fine.

**Comment by drpalli** [comment]
> It also doesn't work for me . It was no response

Hey @cassius425, install it using chocolatey and it installs just fine.

**Comment by BrandoTGreat** [comment]
Just want to chime in here with my Windows 11 install, I tried the normal method of right clicking the .inf, showing more options from the right click context, and clicking install and nothing happened. So I went the chocolatey route and installed first time no problem. I'm not sure why the right click>install didn't work for me but chocolately works fine.

**Comment by imbushuo** [comment]
Use the legacy context menu, or use Device Installer to install.
