### ISSUE TITLE
Testing driver on MacBookPro11,5 (15")

### ISSUE THREAD

**Issue by shawnrc** [imbushuo/mac-precision-touchpad#47]
I've got a 15" Mid-2015 Retina MBP with the following vendor/product IDs:
```
VID_05AC
PID_0274
```

I was wondering if there was a specific branch I should check out and build if I wanted to test this driver on my machine. I'm running Windows 10 x64 1709 (OS Build 16299.192).

Also, is Visual Studio required to build drivers? I have vscode installed and the dotnet stuff running, but afaik that might not be enough.

**Comment by Martin1994** [comment]
I'm trying to debug this driver on my MBA Mid14 as well. AFAIK, you need a Visual Studio (community version is fine), and the Windows Driver Kit, on another Windows machine other than your MBP. In addition, [run WDK Test Target Setup](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/provision-a-target-computer-wdk-8-1) on your MMP.

However, I haven't successfully debugged it yet. My VS always disconnect from the target machine after a deployment. I wish I could have an instruction of setting up a debugging environment.

**Comment by imbushuo** [comment]
Mid-2015 Retina MBP 15inch is expected to be supported. I haven't merged required changes yet.

**Comment by imbushuo** [comment]
@shawnrc I am working on PID 0274. However, I need some information as I don't have such device. Could you measure your touchpad and report its width and length, in centimeters?

**Comment by shawnrc** [comment]
@imbushuo sure! Grabbed a ruler and the approximate measurements are 10.5cm on the long side and 7.7cm on the short one. Let me know if you need more a more precise measure or anything else from me.

**Comment by imbushuo** [comment]
@shawnrc Thanks for the info!

**Comment by fenderguitar** [comment]
@imbushuo I also have a 2015 15" MacBook Pro (Macbookpro11,5)

However my Mac does not contain any SPI devices. 
<img width="863" alt="screen shot 2018-07-19 at 9 04 03 pm" src="https://user-images.githubusercontent.com/23281737/42977796-481a08ec-8b97-11e8-9b92-49796384593a.png">

I have my keyboard under the USB 3.0 Bus.

Apple Internal Keyboard / Trackpad:

  Product ID:	0x0274
  Vendor ID:	0x05ac (Apple Inc.)
  Version:	6.24
  Serial Number:	<>
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Apple Inc.
  Location ID:	0x14400000 / 2
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0
  Built-In:	Yes

**Comment by kurtzy** [comment]
Hi @imbushuo! Just curious if you might have an ETA to have this model supported. Thank you again for this excellent work!

**Comment by imbushuo** [comment]
@kurtzy ETA first week of Oct (the time when my partner can have intensive test on this model)

**Comment by prashantv** [comment]
Anything we can do to help testing or to add this device?

**Comment by kurtzy** [comment]
> Anything we can do to help testing or to add this device?

Happy 2019, and seconded! Happy to help with testing if needed.

**Comment by borb** [comment]
Hello. I have two MacBook Pros, the first a retina 2012 (MacBookPro10,1) with a fully working PTP driver (thanks to this project).

Second is a MacBookPro11,4 with vid 0x05ac/pid 0x0274. Have tried some of the nightly builds (with mentioned IDs in the inf files) and none seem to work sadly. Code 10 when trying the driver. Would gladly offer any help/testing/information as needed.

**Comment by kurtzy** [comment]
Hi @imbushuo - I hope all is well! Would love to see this model supported. I have donated to your project again. Thanks for your work on this project!

**Comment by imbushuo** [comment]
See https://github.com/imbushuo/mac-precision-touchpad/pull/179

**Comment by kurtzy** [comment]
Thanks Bingxing - your driver makes such a huge positive difference and I
really appreciate your efforts. Best wishes for your health and studies!
