### ISSUE TITLE
Is it possible to map the three fingers's click to a windows mid mouse button click?

### ISSUE THREAD

**Issue by xpchenfrank** [imbushuo/mac-precision-touchpad#491]
Hi, thanks for making this driver, but I'm curious is it possible to map the three fingers' click to a windows mid mouse button click?

And also, if we can have some config file to change the action and key mapping would be perfect, for example to change the three finger go left to 'ctrl+shift+tab' to change the three finger go right to 'ctrl+tab', in this case we can easily swtich between chrome tabs.

Anyway, thanks again for sharing this project!

**Comment by JunKuangKuang** [comment]
> 嗨，感谢您制作此驱动程序，但我很好奇是否可以将三个手指的点击映射到 Windows 鼠标中键点击？
> 
> 而且，如果我们可以有一些配置文件来改变动作和键映射将是完美的，例如将三指左移更改为'ctrl+shift+tab' 将三指右移更改为'ctrl+tab '，在这种情况下，我们可以轻松地在 chrome 选项卡之间切换。
> 
> 无论如何，再次感谢分享这个项目！

Hello, how did you solve it?
