### ISSUE TITLE
Link Azure Pipelines to GitHub Releases? 

### ISSUE THREAD

**Issue by rdhar** [imbushuo/mac-precision-touchpad#494]
Hey there, 

Would it be possible to link the output of Azure Pipelines to GitHub's releases in order to reduce manual intervention?

Specifically, there's the [latest Azure #4435](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_build/results?buildId=4435&view=results) for "Added "Magic Trackpad 3" to Device Support (#464)" where the job outputs some [artifacts](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_build/results?buildId=4435&view=artifacts&pathAsName=false&type=publishedArtifacts). However, they're named "PreStage" -- is there another step needed to them release signed? 

From the readme, I learned about the change in Microsoft's drive code signing policy so that must have impacted the CI. Is there any other way for the end-user to locally build and use the drivers from the latest commit, rather than having to wait for manually tagged releases? 

Thanks for sharing this software,
Rishav

**Comment by MagicUtilities** [comment]
To avoid confusion:

1. A **Magic Trackpad 3** does not exist, [more here](https://magicutilities.net/magic-trackpad/faqs?open=magic-trackpad-3).

2. #464 was a change in the README.md file only (that's the main page of this GitHub repository), so there is no need for a new signed driver release.

3. It's almost impossible for kernel drivers releases to be automated as they need to get "cross signed" by Microsoft to run. For this to happen you need an "EV Code Signing Certificate" where only one single version on a hardware USB drive exists. It can't be copied for security reasons.
