### ISSUE TITLE
Macbook Pro Late 2011 (MacBook Pro 8.1) Device Cant Start

### ISSUE THREAD

**Issue by AlvaroMartinezB** [imbushuo/mac-precision-touchpad#51]
Tried installing it onto the Apple Multitouch, and Apple Multitouch mouse devices, neither will work. Device cannot start error 10. Mouse falls back to the windows default driver for touchpads (loosing even the basic Apple scroll)
![capture](https://user-images.githubusercontent.com/14044330/35718545-b4d05c32-07aa-11e8-8799-000457dce5b8.PNG)

**Comment by AlvaroMartinezB** [comment]
Just realized this porblem was noticed in a previews issue thread, will close this one

**Comment by adriankwil** [comment]
> Just realized this porblem was noticed in a previews issue thread, will close this one

could you point me to the thread which helped you solve this issue? I have the same one.
Thanks
