### ISSUE TITLE
CI Builds

### ISSUE THREAD

**Issue by ChristopherHammond13** [imbushuo/mac-precision-touchpad#54]
Hey, 

Would it be possible to get access to the CI builds that come from each branch? The VSTS build badge says that my MSA doesn't have access to that repo. I want to try some of the hid-v2 fixes but as I don't have a valid signing certificate I'd have to remove the 2014 version and install an unsigned version.

Thanks so much for everything you're doing!

**Comment by imbushuo** [comment]
Approved CI builds will be published to GitHub. I will modify the badge's link later so it will point to GitHub. A task will be added so unapproved releases will be published too (but you have to take your own risk trying that, though it will not harm hardware, but a backup mouse is recommended)

**Comment by ChristopherHammond13** [comment]
Amazing, thanks so much!
