### ISSUE TITLE
Magic Trackpad 1

### ISSUE THREAD

**Issue by skyfex** [imbushuo/mac-precision-touchpad#55]
Is it possible to add support for Magic Trackpad 1?

Dependending on how hard it is to set up a development environment, and how much development is needed, I could perhaps contribute the support myself. How hard would it be to implement?

**Comment by imbushuo** [comment]
Add new definitions for HID device. Open USB pipe, start queueing input to I/O queue and finally report to Windows in Windows-defined report format. I haven't checked if MT1 uses the same Linux driver or whether it supports USB or not though.

**Comment by sirburpalot** [comment]
It doesn't. Magic Trackpad 1 is Bluetooth only.

**Comment by imbushuo** [comment]
So it looks like it is not likely to be supported at this moment.
