### ISSUE TITLE
MacBook Pro 13 Early 2015 Support 

### ISSUE THREAD

**Issue by D5T** [imbushuo/mac-precision-touchpad#64]
If you need any help with testing or something else, I'll be glad to help you.

**Comment by vblinden** [comment]
I also have this laptop, if I need to do some testing on my Macbook, it won't be a problem! Keep up the good work!

**Comment by j0hnzzz** [comment]
+1, would be glad if I can help you with the testing of the driver.
Model: MacBookPro12,1

**Comment by imbushuo** [comment]
See #88.
