### ISSUE TITLE
Delay of pressing

### ISSUE THREAD

**Issue by McForse** [imbushuo/mac-precision-touchpad#69]
The driver has a slight delay, touching the trackpad with a finger to make a click.
For example: click on start

**Comment by imbushuo** [comment]
UMDF has higher latency due to it's design, when WHQL thing is cleared, we will move USB driver to KMDF too.

**Comment by insomniality** [comment]
Can delay time be manually adjusted? If not, is it possible to change so that instead of double tapping to do a drag - we just single tap, only with 3 or 2 fingers? That way there wont be any need for the delay!

**Comment by frederikhors** [comment]
I just found out in windows 11 that if you disable the "Tap twice and drag to multi-select" the click delay is gone.

But now I need a way to select the text! LOL!
