### ISSUE TITLE
MacbookAir(5,2)

### ISSUE THREAD

**Issue by Catbirby** [imbushuo/mac-precision-touchpad#73]
I applied the driver to my trackpad, but in device manager, it says that the device has failed to start. with a code 10 error. 

MacBook Air (mid 2012)

**Comment by artistru** [comment]
Hello, I have the same issue.

**Comment by anohren** [comment]
Same here. 

Vendor and product id:
USB\VID_05AC&PID_024D&REV_0219&MI_01

**Comment by imbushuo** [comment]
I pushed a update (not yet signed off the release but it is installation) for your device. Please try https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_build/results?buildId=3734 and see if it works.

Linked to #235.
