### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by nickguo** [imbushuo/mac-precision-touchpad#77]
I've successfully installed the .inf and connected my magic trackpad 2 to my windows desktop, but it doesn't seem to work.

I've connected the MT2 via bluetooth. Are there additional steps I need to take? Also, how do I adjust the sensitivity? (Is there some kind of app to go alongside the drivers?)

**Comment by MasonBergstrom** [comment]
At the moment it only works wired. It sounds like bluetooth pretty much needs its own driver written later.

As for instructions #23 has some instruction in it but, it sounds like you already figured out how to install the inf so that might not be helpful to you.
