### ISSUE TITLE
three finger drag

### ISSUE THREAD

**Issue by shaun92** [imbushuo/mac-precision-touchpad#84]
Thank you for this project. I have completely moved on from trackpad++. Small request if possible can you guys add three finger drag functionality like mac.

**Comment by YeshYyyK** [comment]
It would kind of defeat the purpose. This implementation relies on Windows' Precision Touchpad for all of its stuff. A better idea would be to ask Microsoft to add it in.

**Comment by imbushuo** [comment]
Under current implementation you have to ask Microsoft about it - since it doesn't make sense to expose both mouse HID collection and PTP collection to OS at the same time, and it add cost in processing.
