### ISSUE TITLE
Mouse movement jerky when CPU usage is high

### ISSUE THREAD

**Issue by elaberge** [imbushuo/mac-precision-touchpad#85]
When doing CPU intensive stuff (like compiling a large project), the trackpad becomes very hard to use.

As a workaround, since this is a user-mode driver, increasing the WUDFHost.exe process priority magically makes everything ultra-smooth.

If it is possible to increase thread priority in the code, this would greatly improve the driver performance.

**Comment by imbushuo** [comment]
We will probably merge USB into kernel-mode to reduce the overhead in the future too.
