### ISSUE TITLE
My experience over a month

### ISSUE THREAD

**Issue by YeshYyyK** [imbushuo/mac-precision-touchpad#87]
I've been using this implentation for about a month, and I'm so happy this exists. I'll certainly donate in the future! It's so nice to have an alternative to Trackpad++(esp. with the weird method of 'buying' it). For now, I will be reverting the the Bootcamp drivers, but I'll certainly come back once I see a new release. And if you need me for any testing(rMBP 13" 2014), please feel free to ask.

My major issues:

- The amount of force needed by your finger on the trackpad compared to the Bootcamp driver is quite high. I think reverse-engineering the original Bootcamp driver should fix this.
- Gestures and scrolling are not *that* smooth. Again, I feel that fixing the force needed to detect input above will improve this.
- Occasionally, (as to be expected) , the trackpad isn't (as) responsive, or straight up doesn't work.

Overall, it's really nice to see this.

**Comment by imbushuo** [comment]
Redirects to #94, as well as #93.
