### ISSUE TITLE
Magic Touchpad 2 - Bluetooth Connectivity

### ISSUE THREAD

**Issue by jkhissa** [imbushuo/mac-precision-touchpad#91]
Just want to start with a big thank you for these drivers, they work perfectly as long as the magic touch pad 2 is connected via USB to the computer. 

I am using a pure windows machine, no bootcamp, not a macbook of any kind, just a regular gigabyte laptop. 

When connecting the MTP2 via USB it works fine, exactly as shown in your video. 

When connecting via Bluetooth, without a USB cable, the Magic Touchpad is detected by Windows, and I am able to connect, however it works without the drivers (Bootcamp drivers style) meaning no tap to click, gestures support, or multi finger support. 

I am not raising this is a high priority issue, just a bit of feedback for you in relation to magic touchpad 2 compatibility. 

I just want to know if this behavior is normal or if I didn't install the drivers correctly?

**Comment by imbushuo** [comment]
Bluetooth is not implemented rn, and I don't have much idea about that.

**Comment by jkhissa** [comment]
Thank you

**Comment by deskflag** [comment]
Do u mind implementing the Bluetooth version? I really need wireless connection for it

**Comment by ivo-roilev** [comment]
Same here :(
Still, great drivers, thanks!
