### ISSUE TITLE
MacBook Pro Touch Bar 2016 Support

### ISSUE THREAD

**Issue by Kent-Narun** [imbushuo/mac-precision-touchpad#96]
Can make the driver for MacBook Pro Touch Bar 2016; The devices ID is attached as follow:
<img width="750" alt="screen shot 2018-07-17 at 10 13 04 am" src="https://user-images.githubusercontent.com/41314683/42794797-175e2db6-89ab-11e8-87a9-dc5d9954df51.png">
<img width="751" alt="screen shot 2018-07-17 at 10 13 45 am" src="https://user-images.githubusercontent.com/41314683/42794798-179234d0-89ab-11e8-857c-ddc3f752556f.png">

**Comment by imbushuo** [comment]
`0x0277` is included, which means the SPI driver already implemented support.

https://github.com/imbushuo/mac-precision-touchpad/blob/702e8c518ab052272c2f5f62c33d12a76eb160e2/src/AmtPtpDeviceSpiKm/AmtPtpDeviceSpiKm.inf#L41

The current SPI driver is test-signing (and no binary provided yet), which means you have to enable test signing to install the driver.

**Comment by Kent-Narun** [comment]
Ok so I will wait for the binary then. here is my the tracpad id in windows 10 "SPI\VID_05ac&PID_0277&MI_02"

**Comment by imbushuo** [comment]
@AndrewOCC 

https://github.com/imbushuo/mac-precision-touchpad/blob/702e8c518ab052272c2f5f62c33d12a76eb160e2/src/AmtPtpDeviceSpiKm/AmtPtpDeviceSpiKm.inf#L43

This is included in current implementation too. Currently we are waiting for #95, should be cleared in 2 weeks. (The blocking factor are Dun & Bradstreet and DigiCert)

**Comment by AndrewOCC** [comment]
Great news - congrats on getting to the home stretch

**Comment by monoKeith** [comment]
MacBook Pro late 2016 no-touchbar

Model Identifier:	MacBookPro13,1

Product ID:	0x0276
  Vendor ID:	0x05ac (Apple Inc.)
  ST Version:	8.96
  MT Version:	4.69
  Manufacturer:	Apple Inc.
  Location ID:	0x01000000

**Comment by imbushuo** [comment]
@monoKeith 

https://github.com/imbushuo/mac-precision-touchpad/blob/702e8c518ab052272c2f5f62c33d12a76eb160e2/src/AmtPtpDeviceSpiKm/AmtPtpDeviceSpiKm.inf#L40

Supported too.

**Comment by Rastafabisch** [comment]
Here you got all the relevant information from my model, too. I hope it helps!
Thanks for your efforts! Cheers

<img width="698" alt="macmodel" src="https://user-images.githubusercontent.com/38974866/42994195-ad677ef2-8c0d-11e8-95d3-b6089900a07a.png">
<img width="536" alt="touchpadmodel" src="https://user-images.githubusercontent.com/38974866/42994196-ad8e9294-8c0d-11e8-8404-f9d566fbe4bf.png">

**Comment by imbushuo** [comment]
0278 should be supported per https://github.com/imbushuo/mac-precision-touchpad/blob/702e8c518ab052272c2f5f62c33d12a76eb160e2/src/AmtPtpDeviceSpiKm/AmtPtpDeviceSpiKm.inf.
