### ISSUE TITLE
MacBook Pro (2018)

### ISSUE THREAD

**Issue by imbushuo** [imbushuo/mac-precision-touchpad#97]
If you have a MacBook Pro 2018, please reply below with the device model. I am interested if Apple updated the component or not.

Since MacBook Pro 2018 [implements Secure Boot](https://support.apple.com/en-us/HT208862), drivers need to be Microsoft-signed. We are waiting for #95.

**Comment by karanlyons** [comment]
I don't see any SPI devices listed in System Information, but here's hopefully relevant information from the USB device "Apple Internal Keyboard / Trackpad":

```
  Product ID:	0x027c
  Vendor ID:	0x05ac (Apple Inc.)
  Version:	9.27
  Location ID:	0x80500000 / 3
```

**Comment by imbushuo** [comment]
@karanlyons Thanks for the information. This change is interesting though....

**Comment by S70** [comment]
2018 MacBookPro15,2 13inch TB

```
Product ID:      0x027b
Vendor ID:	0x05ac (Apple Inc.)
Version:	        9.27
Location ID:	0x80500000 / 4

```

**Comment by imbushuo** [comment]
@S70 SPI or USB?

**Comment by S70** [comment]
@imbushuo USB Same location as the above reply

**Comment by imbushuo** [comment]
"He reverted the change"

Thanks for the information.

**Comment by imbushuo** [comment]
Thanks for the information.

**Comment by twodayslate** [comment]
Why was this closed?

**Comment by imbushuo** [comment]
@twodayslate Since the initial model check is completed, this issue is closed (I don't use the issue feature to track model support).
